//! The `xml` grammar's lexer: `ts_lex` and `ts_lex_keywords`, transliterated from
//! its `src/parser.c`, with the symbols and character sets they use.
//!
//! GENERATED BY THE TS_PORT HOST. DO NOT EDIT.
//!
//! Each C `case` is a `match` arm, run once per character: `ADVANCE(n)` and
//! `SKIP(n)` set the state, call `lexer.advance(skip)` and start the next round
//! (C's `goto next_state`), `ACCEPT_TOKEN` sets the result and marks the end, and
//! `END_STATE()` returns the result.
#![allow(non_upper_case_globals, unreachable_code, clippy::all)]

use ts_port_tables::{CharacterRange, Lexer, StateId, Symbol, set_contains};

const anon_sym_AMP: Symbol = 50;
const anon_sym_AMP_POUND: Symbol = 51;
const anon_sym_AMP_POUNDx: Symbol = 53;
const anon_sym_ANY: Symbol = 27;
const anon_sym_ATTLIST: Symbol = 36;
const anon_sym_CDATA: Symbol = 20;
const anon_sym_COMMA: Symbol = 35;
const anon_sym_DOCTYPE: Symbol = 11;
const anon_sym_DQUOTE: Symbol = 9;
const anon_sym_ELEMENT: Symbol = 25;
const anon_sym_EMPTY: Symbol = 26;
const anon_sym_ENTITY: Symbol = 42;
const anon_sym_EQ: Symbol = 65;
const anon_sym_GT: Symbol = 14;
const anon_sym_LBRACK: Symbol = 12;
const anon_sym_LPAREN: Symbol = 28;
const anon_sym_LT: Symbol = 15;
const anon_sym_LT_BANG: Symbol = 10;
const anon_sym_LT_BANG_LBRACK: Symbol = 19;
const anon_sym_LT_QMARK: Symbol = 2;
const anon_sym_LT_SLASH: Symbol = 17;
const anon_sym_NDATA: Symbol = 46;
const anon_sym_NOTATION: Symbol = 38;
const anon_sym_PERCENT: Symbol = 43;
const anon_sym_PIPE: Symbol = 30;
const anon_sym_PLUS: Symbol = 34;
const anon_sym_POUNDFIXED: Symbol = 41;
const anon_sym_POUNDIMPLIED: Symbol = 40;
const anon_sym_POUNDPCDATA: Symbol = 29;
const anon_sym_POUNDREQUIRED: Symbol = 39;
const anon_sym_PUBLIC: Symbol = 56;
const anon_sym_QMARK: Symbol = 33;
const anon_sym_QMARK_GT: Symbol = 4;
const anon_sym_RBRACK: Symbol = 13;
const anon_sym_RBRACK_RBRACK_GT: Symbol = 18;
const anon_sym_RPAREN: Symbol = 31;
const anon_sym_SEMI: Symbol = 47;
const anon_sym_SLASH_GT: Symbol = 16;
const anon_sym_SQUOTE: Symbol = 6;
const anon_sym_STAR: Symbol = 32;
const anon_sym_SYSTEM: Symbol = 55;
const anon_sym_encoding: Symbol = 63;
const anon_sym_no: Symbol = 8;
const anon_sym_standalone: Symbol = 5;
const anon_sym_version: Symbol = 61;
const anon_sym_xml: Symbol = 3;
const anon_sym_xml_DASHmodel: Symbol = 22;
const anon_sym_xml_DASHstylesheet: Symbol = 21;
const anon_sym_yes: Symbol = 7;
const aux_sym_CharRef_token1: Symbol = 52;
const aux_sym_CharRef_token2: Symbol = 54;
const aux_sym_EntityValue_token1: Symbol = 44;
const aux_sym_EntityValue_token2: Symbol = 45;
const aux_sym_PseudoAttValue_token1: Symbol = 23;
const aux_sym_PseudoAttValue_token2: Symbol = 24;
const aux_sym_PubidLiteral_token1: Symbol = 59;
const aux_sym_PubidLiteral_token2: Symbol = 60;
const aux_sym_SystemLiteral_token1: Symbol = 57;
const aux_sym_SystemLiteral_token2: Symbol = 58;
const sym_EncName: Symbol = 64;
const sym_Name: Symbol = 1;
const sym_Nmtoken: Symbol = 49;
const sym_TokenizedType: Symbol = 37;
const sym_VersionNum: Symbol = 62;
const sym__S: Symbol = 48;
const ts_builtin_sym_end: Symbol = 0;

#[rustfmt::skip]
static aux_sym_PubidLiteral_token1_character_set_1: [CharacterRange; 9] = [
    CharacterRange::new(10, 10), CharacterRange::new(13, 13), CharacterRange::new(32, 33), CharacterRange::new(35, 37), CharacterRange::new(39, 59), CharacterRange::new(61, 61),
    CharacterRange::new(63, 90), CharacterRange::new(95, 95), CharacterRange::new(97, 122),
];

#[rustfmt::skip]
static aux_sym_PubidLiteral_token2_character_set_1: [CharacterRange; 9] = [
    CharacterRange::new(10, 10), CharacterRange::new(13, 13), CharacterRange::new(32, 33), CharacterRange::new(35, 37), CharacterRange::new(40, 59), CharacterRange::new(61, 61),
    CharacterRange::new(63, 90), CharacterRange::new(95, 95), CharacterRange::new(97, 122),
];

/// `ADVANCE_MAP`: the state paired with the first key equal to `lookahead`.
fn advance_map(map: &[(u16, StateId)], lookahead: i32) -> Option<StateId> {
    map.iter()
        .find(|&&(key, _)| i32::from(key) == lookahead)
        .map(|&(_, state)| state)
}

/// C's `ts_lex`: lexes one token from lex state `state`; returns whether it
/// accepted one.
#[rustfmt::skip]
pub(crate) fn ts_lex(lexer: &mut dyn Lexer, mut state: StateId) -> bool {
    let mut result = false;
    loop {
        // C's `start:` label (reached again after each `next_state:` advance).
        let lookahead = lexer.lookahead();
        let eof = lexer.eof();
        match state {
            0 => {
                if eof { state = 42; lexer.advance(false); continue; }
                if let Some(next) = advance_map(&[
                    (34, 46), (35, 64), (37, 91), (38, 132), (39, 45), (40, 74), (41, 77), (42, 78),
                    (43, 80), (44, 81), (47, 62), (49, 61), (59, 94), (60, 53), (61, 143), (62, 52),
                    (63, 79), (69, 66), (73, 63), (78, 65), (91, 49), (93, 51), (95, 72), (124, 76),
                    (9, 69), (10, 69), (13, 69), (32, 69), (45, 71), (46, 71), (58, 71), (183, 71),
                ], lookahead) { state = next; lexer.advance(false); continue; }
                if 48 <= lookahead && lookahead <= 57 { state = 70; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 70 || 97 <= lookahead && lookahead <= 102 { state = 67; lexer.advance(false); continue; }
                if 71 <= lookahead && lookahead <= 90 || 103 <= lookahead && lookahead <= 122 { state = 68; lexer.advance(false); continue; }
                if lookahead != 0 { state = 60; lexer.advance(false); continue; }
                return result;
            }
            1 => {
                if let Some(next) = advance_map(&[
                    (34, 46), (35, 28), (37, 91), (39, 45), (40, 74), (41, 77), (42, 78), (43, 80),
                    (44, 81), (47, 7), (62, 52), (63, 79), (91, 49), (93, 36), (124, 76), (9, 95),
                    (10, 95), (13, 95), (32, 95),
                ], lookahead) { state = next; lexer.advance(false); continue; }
                if 48 <= lookahead && lookahead <= 57 { state = 134; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            2 => {
                if lookahead == 34 { state = 46; lexer.advance(false); continue; }
                if lookahead == 37 { state = 91; lexer.advance(false); continue; }
                if lookahead == 38 { state = 132; lexer.advance(false); continue; }
                if lookahead != 0 && lookahead != 60 { state = 92; lexer.advance(false); continue; }
                return result;
            }
            3 => {
                if lookahead == 34 { state = 46; lexer.advance(false); continue; }
                if lookahead == 38 { state = 132; lexer.advance(false); continue; }
                if lookahead != 0 && lookahead != 60 { state = 60; lexer.advance(false); continue; }
                return result;
            }
            4 => {
                if lookahead == 37 { state = 91; lexer.advance(false); continue; }
                if lookahead == 38 { state = 132; lexer.advance(false); continue; }
                if lookahead == 39 { state = 45; lexer.advance(false); continue; }
                if lookahead == 60 { state = 55; lexer.advance(false); continue; }
                if lookahead != 0 { state = 93; lexer.advance(false); continue; }
                return result;
            }
            5 => {
                if lookahead == 38 { state = 132; lexer.advance(false); continue; }
                if lookahead == 39 { state = 45; lexer.advance(false); continue; }
                if lookahead != 0 && lookahead != 60 { state = 73; lexer.advance(false); continue; }
                return result;
            }
            6 => {
                if lookahead == 46 { state = 38; lexer.advance(false); continue; }
                return result;
            }
            7 => {
                if lookahead == 62 { state = 56; lexer.advance(false); continue; }
                return result;
            }
            8 => {
                if lookahead == 62 { state = 58; lexer.advance(false); continue; }
                return result;
            }
            9 => {
                if lookahead == 62 { state = 44; lexer.advance(false); continue; }
                return result;
            }
            10 => {
                if lookahead == 63 { state = 9; lexer.advance(false); continue; }
                if lookahead == 9 || lookahead == 10 || lookahead == 13 || lookahead == 32 { state = 95; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            11 => {
                if lookahead == 65 { state = 32; lexer.advance(false); continue; }
                return result;
            }
            12 => {
                if lookahead == 65 { state = 75; lexer.advance(false); continue; }
                return result;
            }
            13 => {
                if lookahead == 67 { state = 14; lexer.advance(false); continue; }
                return result;
            }
            14 => {
                if lookahead == 68 { state = 11; lexer.advance(false); continue; }
                return result;
            }
            15 => {
                if lookahead == 68 { state = 90; lexer.advance(false); continue; }
                return result;
            }
            16 => {
                if lookahead == 68 { state = 89; lexer.advance(false); continue; }
                return result;
            }
            17 => {
                if lookahead == 68 { state = 88; lexer.advance(false); continue; }
                return result;
            }
            18 => {
                if lookahead == 69 { state = 30; lexer.advance(false); continue; }
                return result;
            }
            19 => {
                if lookahead == 69 { state = 15; lexer.advance(false); continue; }
                return result;
            }
            20 => {
                if lookahead == 69 { state = 16; lexer.advance(false); continue; }
                return result;
            }
            21 => {
                if lookahead == 69 { state = 17; lexer.advance(false); continue; }
                return result;
            }
            22 => {
                if lookahead == 70 { state = 23; lexer.advance(false); continue; }
                if lookahead == 73 { state = 27; lexer.advance(false); continue; }
                if lookahead == 82 { state = 18; lexer.advance(false); continue; }
                return result;
            }
            23 => {
                if lookahead == 73 { state = 34; lexer.advance(false); continue; }
                return result;
            }
            24 => {
                if lookahead == 73 { state = 31; lexer.advance(false); continue; }
                return result;
            }
            25 => {
                if lookahead == 73 { state = 20; lexer.advance(false); continue; }
                return result;
            }
            26 => {
                if lookahead == 76 { state = 25; lexer.advance(false); continue; }
                return result;
            }
            27 => {
                if lookahead == 77 { state = 29; lexer.advance(false); continue; }
                return result;
            }
            28 => {
                if lookahead == 80 { state = 13; lexer.advance(false); continue; }
                return result;
            }
            29 => {
                if lookahead == 80 { state = 26; lexer.advance(false); continue; }
                return result;
            }
            30 => {
                if lookahead == 81 { state = 33; lexer.advance(false); continue; }
                return result;
            }
            31 => {
                if lookahead == 82 { state = 21; lexer.advance(false); continue; }
                return result;
            }
            32 => {
                if lookahead == 84 { state = 12; lexer.advance(false); continue; }
                return result;
            }
            33 => {
                if lookahead == 85 { state = 24; lexer.advance(false); continue; }
                return result;
            }
            34 => {
                if lookahead == 88 { state = 19; lexer.advance(false); continue; }
                return result;
            }
            35 => {
                if lookahead == 91 { state = 59; lexer.advance(false); continue; }
                return result;
            }
            36 => {
                if lookahead == 93 { state = 8; lexer.advance(false); continue; }
                return result;
            }
            37 => {
                if lookahead == 9 || lookahead == 10 || lookahead == 13 || lookahead == 32 { state = 95; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 131; lexer.advance(false); continue; }
                return result;
            }
            38 => {
                if 48 <= lookahead && lookahead <= 57 { state = 141; lexer.advance(false); continue; }
                return result;
            }
            39 => {
                if 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 70 || 97 <= lookahead && lookahead <= 102 { state = 136; lexer.advance(false); continue; }
                return result;
            }
            40 => {
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 142; lexer.advance(false); continue; }
                return result;
            }
            41 => {
                if eof { state = 42; lexer.advance(false); continue; }
                if let Some(next) = advance_map(&[
                    (34, 46), (35, 22), (37, 91), (39, 45), (40, 74), (41, 77), (42, 78), (43, 80),
                    (44, 81), (47, 7), (49, 6), (59, 94), (60, 54), (61, 143), (62, 52), (63, 79),
                    (69, 113), (73, 96), (78, 111), (91, 49), (93, 50), (124, 76), (9, 95), (10, 95),
                    (13, 95), (32, 95),
                ], lookahead) { state = next; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            42 => {
                result = true; lexer.set_result_symbol(ts_builtin_sym_end); lexer.mark_end();
                return result;
            }
            43 => {
                result = true; lexer.set_result_symbol(anon_sym_LT_QMARK); lexer.mark_end();
                return result;
            }
            44 => {
                result = true; lexer.set_result_symbol(anon_sym_QMARK_GT); lexer.mark_end();
                return result;
            }
            45 => {
                result = true; lexer.set_result_symbol(anon_sym_SQUOTE); lexer.mark_end();
                return result;
            }
            46 => {
                result = true; lexer.set_result_symbol(anon_sym_DQUOTE); lexer.mark_end();
                return result;
            }
            47 => {
                result = true; lexer.set_result_symbol(anon_sym_LT_BANG); lexer.mark_end();
                return result;
            }
            48 => {
                result = true; lexer.set_result_symbol(anon_sym_LT_BANG); lexer.mark_end();
                if lookahead == 91 { state = 59; lexer.advance(false); continue; }
                return result;
            }
            49 => {
                result = true; lexer.set_result_symbol(anon_sym_LBRACK); lexer.mark_end();
                return result;
            }
            50 => {
                result = true; lexer.set_result_symbol(anon_sym_RBRACK); lexer.mark_end();
                return result;
            }
            51 => {
                result = true; lexer.set_result_symbol(anon_sym_RBRACK); lexer.mark_end();
                if lookahead == 93 { state = 8; lexer.advance(false); continue; }
                return result;
            }
            52 => {
                result = true; lexer.set_result_symbol(anon_sym_GT); lexer.mark_end();
                return result;
            }
            53 => {
                result = true; lexer.set_result_symbol(anon_sym_LT); lexer.mark_end();
                if lookahead == 33 { state = 48; lexer.advance(false); continue; }
                if lookahead == 47 { state = 57; lexer.advance(false); continue; }
                if lookahead == 63 { state = 43; lexer.advance(false); continue; }
                return result;
            }
            54 => {
                result = true; lexer.set_result_symbol(anon_sym_LT); lexer.mark_end();
                if lookahead == 33 { state = 47; lexer.advance(false); continue; }
                if lookahead == 63 { state = 43; lexer.advance(false); continue; }
                return result;
            }
            55 => {
                result = true; lexer.set_result_symbol(anon_sym_LT); lexer.mark_end();
                if lookahead == 33 { state = 35; lexer.advance(false); continue; }
                if lookahead == 47 { state = 57; lexer.advance(false); continue; }
                if lookahead == 63 { state = 43; lexer.advance(false); continue; }
                return result;
            }
            56 => {
                result = true; lexer.set_result_symbol(anon_sym_SLASH_GT); lexer.mark_end();
                return result;
            }
            57 => {
                result = true; lexer.set_result_symbol(anon_sym_LT_SLASH); lexer.mark_end();
                return result;
            }
            58 => {
                result = true; lexer.set_result_symbol(anon_sym_RBRACK_RBRACK_GT); lexer.mark_end();
                return result;
            }
            59 => {
                result = true; lexer.set_result_symbol(anon_sym_LT_BANG_LBRACK); lexer.mark_end();
                return result;
            }
            60 => {
                result = true; lexer.set_result_symbol(aux_sym_PseudoAttValue_token1); lexer.mark_end();
                return result;
            }
            61 => {
                result = true; lexer.set_result_symbol(aux_sym_PseudoAttValue_token1); lexer.mark_end();
                if lookahead == 46 { state = 128; lexer.advance(false); continue; }
                if 48 <= lookahead && lookahead <= 57 { state = 129; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 70 || 97 <= lookahead && lookahead <= 102 { state = 130; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 58 || 71 <= lookahead && lookahead <= 90 || lookahead == 95 || 103 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 131; lexer.advance(false); continue; }
                return result;
            }
            62 => {
                result = true; lexer.set_result_symbol(aux_sym_PseudoAttValue_token1); lexer.mark_end();
                if lookahead == 62 { state = 56; lexer.advance(false); continue; }
                return result;
            }
            63 => {
                result = true; lexer.set_result_symbol(aux_sym_PseudoAttValue_token1); lexer.mark_end();
                if lookahead == 68 { state = 82; lexer.advance(false); continue; }
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            64 => {
                result = true; lexer.set_result_symbol(aux_sym_PseudoAttValue_token1); lexer.mark_end();
                if lookahead == 70 { state = 23; lexer.advance(false); continue; }
                if lookahead == 73 { state = 27; lexer.advance(false); continue; }
                if lookahead == 80 { state = 13; lexer.advance(false); continue; }
                if lookahead == 82 { state = 18; lexer.advance(false); continue; }
                return result;
            }
            65 => {
                result = true; lexer.set_result_symbol(aux_sym_PseudoAttValue_token1); lexer.mark_end();
                if lookahead == 77 { state = 120; lexer.advance(false); continue; }
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            66 => {
                result = true; lexer.set_result_symbol(aux_sym_PseudoAttValue_token1); lexer.mark_end();
                if lookahead == 78 { state = 119; lexer.advance(false); continue; }
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 70 || 97 <= lookahead && lookahead <= 102 { state = 125; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 71 <= lookahead && lookahead <= 90 || lookahead == 95 || 103 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            67 => {
                result = true; lexer.set_result_symbol(aux_sym_PseudoAttValue_token1); lexer.mark_end();
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 70 || 97 <= lookahead && lookahead <= 102 { state = 125; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 71 <= lookahead && lookahead <= 90 || lookahead == 95 || 103 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            68 => {
                result = true; lexer.set_result_symbol(aux_sym_PseudoAttValue_token1); lexer.mark_end();
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            69 => {
                result = true; lexer.set_result_symbol(aux_sym_PseudoAttValue_token1); lexer.mark_end();
                if lookahead == 9 || lookahead == 10 || lookahead == 13 || lookahead == 32 { state = 95; lexer.advance(false); continue; }
                return result;
            }
            70 => {
                result = true; lexer.set_result_symbol(aux_sym_PseudoAttValue_token1); lexer.mark_end();
                if 48 <= lookahead && lookahead <= 57 { state = 129; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 70 || 97 <= lookahead && lookahead <= 102 { state = 130; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || lookahead == 58 || 71 <= lookahead && lookahead <= 90 || lookahead == 95 || 103 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 131; lexer.advance(false); continue; }
                return result;
            }
            71 => {
                result = true; lexer.set_result_symbol(aux_sym_PseudoAttValue_token1); lexer.mark_end();
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 131; lexer.advance(false); continue; }
                return result;
            }
            72 => {
                result = true; lexer.set_result_symbol(aux_sym_PseudoAttValue_token1); lexer.mark_end();
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            73 => {
                result = true; lexer.set_result_symbol(aux_sym_PseudoAttValue_token2); lexer.mark_end();
                return result;
            }
            74 => {
                result = true; lexer.set_result_symbol(anon_sym_LPAREN); lexer.mark_end();
                return result;
            }
            75 => {
                result = true; lexer.set_result_symbol(anon_sym_POUNDPCDATA); lexer.mark_end();
                return result;
            }
            76 => {
                result = true; lexer.set_result_symbol(anon_sym_PIPE); lexer.mark_end();
                return result;
            }
            77 => {
                result = true; lexer.set_result_symbol(anon_sym_RPAREN); lexer.mark_end();
                return result;
            }
            78 => {
                result = true; lexer.set_result_symbol(anon_sym_STAR); lexer.mark_end();
                return result;
            }
            79 => {
                result = true; lexer.set_result_symbol(anon_sym_QMARK); lexer.mark_end();
                return result;
            }
            80 => {
                result = true; lexer.set_result_symbol(anon_sym_PLUS); lexer.mark_end();
                return result;
            }
            81 => {
                result = true; lexer.set_result_symbol(anon_sym_COMMA); lexer.mark_end();
                return result;
            }
            82 => {
                result = true; lexer.set_result_symbol(sym_TokenizedType); lexer.mark_end();
                if lookahead == 82 { state = 97; lexer.advance(false); continue; }
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            83 => {
                result = true; lexer.set_result_symbol(sym_TokenizedType); lexer.mark_end();
                if lookahead == 82 { state = 100; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            84 => {
                result = true; lexer.set_result_symbol(sym_TokenizedType); lexer.mark_end();
                if lookahead == 83 { state = 86; lexer.advance(false); continue; }
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            85 => {
                result = true; lexer.set_result_symbol(sym_TokenizedType); lexer.mark_end();
                if lookahead == 83 { state = 87; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            86 => {
                result = true; lexer.set_result_symbol(sym_TokenizedType); lexer.mark_end();
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            87 => {
                result = true; lexer.set_result_symbol(sym_TokenizedType); lexer.mark_end();
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            88 => {
                result = true; lexer.set_result_symbol(anon_sym_POUNDREQUIRED); lexer.mark_end();
                return result;
            }
            89 => {
                result = true; lexer.set_result_symbol(anon_sym_POUNDIMPLIED); lexer.mark_end();
                return result;
            }
            90 => {
                result = true; lexer.set_result_symbol(anon_sym_POUNDFIXED); lexer.mark_end();
                return result;
            }
            91 => {
                result = true; lexer.set_result_symbol(anon_sym_PERCENT); lexer.mark_end();
                return result;
            }
            92 => {
                result = true; lexer.set_result_symbol(aux_sym_EntityValue_token1); lexer.mark_end();
                return result;
            }
            93 => {
                result = true; lexer.set_result_symbol(aux_sym_EntityValue_token2); lexer.mark_end();
                return result;
            }
            94 => {
                result = true; lexer.set_result_symbol(anon_sym_SEMI); lexer.mark_end();
                return result;
            }
            95 => {
                result = true; lexer.set_result_symbol(sym__S); lexer.mark_end();
                if lookahead == 9 || lookahead == 10 || lookahead == 13 || lookahead == 32 { state = 95; lexer.advance(false); continue; }
                return result;
            }
            96 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 68 { state = 83; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            97 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 69 { state = 103; lexer.advance(false); continue; }
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            98 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 69 { state = 112; lexer.advance(false); continue; }
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            99 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 69 { state = 117; lexer.advance(false); continue; }
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            100 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 69 { state = 104; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            101 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 69 { state = 118; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            102 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 69 { state = 114; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            103 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 70 { state = 84; lexer.advance(false); continue; }
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            104 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 70 { state = 85; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            105 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 73 { state = 121; lexer.advance(false); continue; }
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            106 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 73 { state = 99; lexer.advance(false); continue; }
                if lookahead == 89 { state = 86; lexer.advance(false); continue; }
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            107 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 73 { state = 124; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            108 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 73 { state = 101; lexer.advance(false); continue; }
                if lookahead == 89 { state = 87; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            109 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 75 { state = 98; lexer.advance(false); continue; }
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            110 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 75 { state = 102; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            111 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 77 { state = 123; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            112 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 78 { state = 84; lexer.advance(false); continue; }
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            113 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 78 { state = 122; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            114 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 78 { state = 85; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            115 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 79 { state = 109; lexer.advance(false); continue; }
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            116 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 79 { state = 110; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            117 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 83 { state = 86; lexer.advance(false); continue; }
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            118 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 83 { state = 87; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            119 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 84 { state = 105; lexer.advance(false); continue; }
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            120 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 84 { state = 115; lexer.advance(false); continue; }
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            121 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 84 { state = 106; lexer.advance(false); continue; }
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            122 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 84 { state = 107; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            123 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 84 { state = 116; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            124 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 84 { state = 108; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            125 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 70 || 97 <= lookahead && lookahead <= 102 { state = 125; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 71 <= lookahead && lookahead <= 90 || lookahead == 95 || 103 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            126 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 58 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 126; lexer.advance(false); continue; }
                return result;
            }
            127 => {
                result = true; lexer.set_result_symbol(sym_Name); lexer.mark_end();
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 127; lexer.advance(false); continue; }
                return result;
            }
            128 => {
                result = true; lexer.set_result_symbol(sym_Nmtoken); lexer.mark_end();
                if 48 <= lookahead && lookahead <= 57 { state = 128; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || lookahead == 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 131; lexer.advance(false); continue; }
                return result;
            }
            129 => {
                result = true; lexer.set_result_symbol(sym_Nmtoken); lexer.mark_end();
                if 48 <= lookahead && lookahead <= 57 { state = 129; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 70 || 97 <= lookahead && lookahead <= 102 { state = 130; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || lookahead == 58 || 71 <= lookahead && lookahead <= 90 || lookahead == 95 || 103 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 131; lexer.advance(false); continue; }
                return result;
            }
            130 => {
                result = true; lexer.set_result_symbol(sym_Nmtoken); lexer.mark_end();
                if 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 70 || 97 <= lookahead && lookahead <= 102 { state = 130; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 46 || lookahead == 58 || 71 <= lookahead && lookahead <= 90 || lookahead == 95 || 103 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 131; lexer.advance(false); continue; }
                return result;
            }
            131 => {
                result = true; lexer.set_result_symbol(sym_Nmtoken); lexer.mark_end();
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 58 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 || lookahead == 183 { state = 131; lexer.advance(false); continue; }
                return result;
            }
            132 => {
                result = true; lexer.set_result_symbol(anon_sym_AMP); lexer.mark_end();
                if lookahead == 35 { state = 133; lexer.advance(false); continue; }
                return result;
            }
            133 => {
                result = true; lexer.set_result_symbol(anon_sym_AMP_POUND); lexer.mark_end();
                if lookahead == 120 { state = 135; lexer.advance(false); continue; }
                return result;
            }
            134 => {
                result = true; lexer.set_result_symbol(aux_sym_CharRef_token1); lexer.mark_end();
                if 48 <= lookahead && lookahead <= 57 { state = 134; lexer.advance(false); continue; }
                return result;
            }
            135 => {
                result = true; lexer.set_result_symbol(anon_sym_AMP_POUNDx); lexer.mark_end();
                return result;
            }
            136 => {
                result = true; lexer.set_result_symbol(aux_sym_CharRef_token2); lexer.mark_end();
                if 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 70 || 97 <= lookahead && lookahead <= 102 { state = 136; lexer.advance(false); continue; }
                return result;
            }
            137 => {
                result = true; lexer.set_result_symbol(aux_sym_SystemLiteral_token1); lexer.mark_end();
                if lookahead != 0 && lookahead != 34 { state = 137; lexer.advance(false); continue; }
                return result;
            }
            138 => {
                result = true; lexer.set_result_symbol(aux_sym_SystemLiteral_token2); lexer.mark_end();
                if lookahead != 0 && lookahead != 39 { state = 138; lexer.advance(false); continue; }
                return result;
            }
            139 => {
                result = true; lexer.set_result_symbol(aux_sym_PubidLiteral_token1); lexer.mark_end();
                if set_contains(&aux_sym_PubidLiteral_token1_character_set_1, lookahead) { state = 139; lexer.advance(false); continue; }
                return result;
            }
            140 => {
                result = true; lexer.set_result_symbol(aux_sym_PubidLiteral_token2); lexer.mark_end();
                if set_contains(&aux_sym_PubidLiteral_token2_character_set_1, lookahead) { state = 140; lexer.advance(false); continue; }
                return result;
            }
            141 => {
                result = true; lexer.set_result_symbol(sym_VersionNum); lexer.mark_end();
                if 48 <= lookahead && lookahead <= 57 { state = 141; lexer.advance(false); continue; }
                return result;
            }
            142 => {
                result = true; lexer.set_result_symbol(sym_EncName); lexer.mark_end();
                if lookahead == 45 || lookahead == 46 || 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 142; lexer.advance(false); continue; }
                return result;
            }
            143 => {
                result = true; lexer.set_result_symbol(anon_sym_EQ); lexer.mark_end();
                return result;
            }
            _ => return false,
        }
    }
}

/// C's `ts_lex_keywords`: lexes one token from lex state `state`; returns whether it
/// accepted one.
#[rustfmt::skip]
pub(crate) fn ts_lex_keywords(lexer: &mut dyn Lexer, mut state: StateId) -> bool {
    let mut result = false;
    loop {
        // C's `start:` label (reached again after each `next_state:` advance).
        let lookahead = lexer.lookahead();
        let _eof = lexer.eof();
        match state {
            0 => {
                if let Some(next) = advance_map(&[
                    (65, 1), (67, 2), (68, 3), (69, 4), (78, 5), (80, 6), (83, 7), (101, 8),
                    (110, 9), (115, 10), (118, 11), (120, 12), (121, 13),
                ], lookahead) { state = next; lexer.advance(false); continue; }
                return result;
            }
            1 => {
                if lookahead == 78 { state = 14; lexer.advance(false); continue; }
                if lookahead == 84 { state = 15; lexer.advance(false); continue; }
                return result;
            }
            2 => {
                if lookahead == 68 { state = 16; lexer.advance(false); continue; }
                return result;
            }
            3 => {
                if lookahead == 79 { state = 17; lexer.advance(false); continue; }
                return result;
            }
            4 => {
                if lookahead == 76 { state = 18; lexer.advance(false); continue; }
                if lookahead == 77 { state = 19; lexer.advance(false); continue; }
                if lookahead == 78 { state = 20; lexer.advance(false); continue; }
                return result;
            }
            5 => {
                if lookahead == 68 { state = 21; lexer.advance(false); continue; }
                if lookahead == 79 { state = 22; lexer.advance(false); continue; }
                return result;
            }
            6 => {
                if lookahead == 85 { state = 23; lexer.advance(false); continue; }
                return result;
            }
            7 => {
                if lookahead == 89 { state = 24; lexer.advance(false); continue; }
                return result;
            }
            8 => {
                if lookahead == 110 { state = 25; lexer.advance(false); continue; }
                return result;
            }
            9 => {
                if lookahead == 111 { state = 26; lexer.advance(false); continue; }
                return result;
            }
            10 => {
                if lookahead == 116 { state = 27; lexer.advance(false); continue; }
                return result;
            }
            11 => {
                if lookahead == 101 { state = 28; lexer.advance(false); continue; }
                return result;
            }
            12 => {
                if lookahead == 109 { state = 29; lexer.advance(false); continue; }
                return result;
            }
            13 => {
                if lookahead == 101 { state = 30; lexer.advance(false); continue; }
                return result;
            }
            14 => {
                if lookahead == 89 { state = 31; lexer.advance(false); continue; }
                return result;
            }
            15 => {
                if lookahead == 84 { state = 32; lexer.advance(false); continue; }
                return result;
            }
            16 => {
                if lookahead == 65 { state = 33; lexer.advance(false); continue; }
                return result;
            }
            17 => {
                if lookahead == 67 { state = 34; lexer.advance(false); continue; }
                return result;
            }
            18 => {
                if lookahead == 69 { state = 35; lexer.advance(false); continue; }
                return result;
            }
            19 => {
                if lookahead == 80 { state = 36; lexer.advance(false); continue; }
                return result;
            }
            20 => {
                if lookahead == 84 { state = 37; lexer.advance(false); continue; }
                return result;
            }
            21 => {
                if lookahead == 65 { state = 38; lexer.advance(false); continue; }
                return result;
            }
            22 => {
                if lookahead == 84 { state = 39; lexer.advance(false); continue; }
                return result;
            }
            23 => {
                if lookahead == 66 { state = 40; lexer.advance(false); continue; }
                return result;
            }
            24 => {
                if lookahead == 83 { state = 41; lexer.advance(false); continue; }
                return result;
            }
            25 => {
                if lookahead == 99 { state = 42; lexer.advance(false); continue; }
                return result;
            }
            26 => {
                result = true; lexer.set_result_symbol(anon_sym_no); lexer.mark_end();
                return result;
            }
            27 => {
                if lookahead == 97 { state = 43; lexer.advance(false); continue; }
                return result;
            }
            28 => {
                if lookahead == 114 { state = 44; lexer.advance(false); continue; }
                return result;
            }
            29 => {
                if lookahead == 108 { state = 45; lexer.advance(false); continue; }
                return result;
            }
            30 => {
                if lookahead == 115 { state = 46; lexer.advance(false); continue; }
                return result;
            }
            31 => {
                result = true; lexer.set_result_symbol(anon_sym_ANY); lexer.mark_end();
                return result;
            }
            32 => {
                if lookahead == 76 { state = 47; lexer.advance(false); continue; }
                return result;
            }
            33 => {
                if lookahead == 84 { state = 48; lexer.advance(false); continue; }
                return result;
            }
            34 => {
                if lookahead == 84 { state = 49; lexer.advance(false); continue; }
                return result;
            }
            35 => {
                if lookahead == 77 { state = 50; lexer.advance(false); continue; }
                return result;
            }
            36 => {
                if lookahead == 84 { state = 51; lexer.advance(false); continue; }
                return result;
            }
            37 => {
                if lookahead == 73 { state = 52; lexer.advance(false); continue; }
                return result;
            }
            38 => {
                if lookahead == 84 { state = 53; lexer.advance(false); continue; }
                return result;
            }
            39 => {
                if lookahead == 65 { state = 54; lexer.advance(false); continue; }
                return result;
            }
            40 => {
                if lookahead == 76 { state = 55; lexer.advance(false); continue; }
                return result;
            }
            41 => {
                if lookahead == 84 { state = 56; lexer.advance(false); continue; }
                return result;
            }
            42 => {
                if lookahead == 111 { state = 57; lexer.advance(false); continue; }
                return result;
            }
            43 => {
                if lookahead == 110 { state = 58; lexer.advance(false); continue; }
                return result;
            }
            44 => {
                if lookahead == 115 { state = 59; lexer.advance(false); continue; }
                return result;
            }
            45 => {
                result = true; lexer.set_result_symbol(anon_sym_xml); lexer.mark_end();
                if lookahead == 45 { state = 60; lexer.advance(false); continue; }
                return result;
            }
            46 => {
                result = true; lexer.set_result_symbol(anon_sym_yes); lexer.mark_end();
                return result;
            }
            47 => {
                if lookahead == 73 { state = 61; lexer.advance(false); continue; }
                return result;
            }
            48 => {
                if lookahead == 65 { state = 62; lexer.advance(false); continue; }
                return result;
            }
            49 => {
                if lookahead == 89 { state = 63; lexer.advance(false); continue; }
                return result;
            }
            50 => {
                if lookahead == 69 { state = 64; lexer.advance(false); continue; }
                return result;
            }
            51 => {
                if lookahead == 89 { state = 65; lexer.advance(false); continue; }
                return result;
            }
            52 => {
                if lookahead == 84 { state = 66; lexer.advance(false); continue; }
                return result;
            }
            53 => {
                if lookahead == 65 { state = 67; lexer.advance(false); continue; }
                return result;
            }
            54 => {
                if lookahead == 84 { state = 68; lexer.advance(false); continue; }
                return result;
            }
            55 => {
                if lookahead == 73 { state = 69; lexer.advance(false); continue; }
                return result;
            }
            56 => {
                if lookahead == 69 { state = 70; lexer.advance(false); continue; }
                return result;
            }
            57 => {
                if lookahead == 100 { state = 71; lexer.advance(false); continue; }
                return result;
            }
            58 => {
                if lookahead == 100 { state = 72; lexer.advance(false); continue; }
                return result;
            }
            59 => {
                if lookahead == 105 { state = 73; lexer.advance(false); continue; }
                return result;
            }
            60 => {
                if lookahead == 109 { state = 74; lexer.advance(false); continue; }
                if lookahead == 115 { state = 75; lexer.advance(false); continue; }
                return result;
            }
            61 => {
                if lookahead == 83 { state = 76; lexer.advance(false); continue; }
                return result;
            }
            62 => {
                result = true; lexer.set_result_symbol(anon_sym_CDATA); lexer.mark_end();
                return result;
            }
            63 => {
                if lookahead == 80 { state = 77; lexer.advance(false); continue; }
                return result;
            }
            64 => {
                if lookahead == 78 { state = 78; lexer.advance(false); continue; }
                return result;
            }
            65 => {
                result = true; lexer.set_result_symbol(anon_sym_EMPTY); lexer.mark_end();
                return result;
            }
            66 => {
                if lookahead == 89 { state = 79; lexer.advance(false); continue; }
                return result;
            }
            67 => {
                result = true; lexer.set_result_symbol(anon_sym_NDATA); lexer.mark_end();
                return result;
            }
            68 => {
                if lookahead == 73 { state = 80; lexer.advance(false); continue; }
                return result;
            }
            69 => {
                if lookahead == 67 { state = 81; lexer.advance(false); continue; }
                return result;
            }
            70 => {
                if lookahead == 77 { state = 82; lexer.advance(false); continue; }
                return result;
            }
            71 => {
                if lookahead == 105 { state = 83; lexer.advance(false); continue; }
                return result;
            }
            72 => {
                if lookahead == 97 { state = 84; lexer.advance(false); continue; }
                return result;
            }
            73 => {
                if lookahead == 111 { state = 85; lexer.advance(false); continue; }
                return result;
            }
            74 => {
                if lookahead == 111 { state = 86; lexer.advance(false); continue; }
                return result;
            }
            75 => {
                if lookahead == 116 { state = 87; lexer.advance(false); continue; }
                return result;
            }
            76 => {
                if lookahead == 84 { state = 88; lexer.advance(false); continue; }
                return result;
            }
            77 => {
                if lookahead == 69 { state = 89; lexer.advance(false); continue; }
                return result;
            }
            78 => {
                if lookahead == 84 { state = 90; lexer.advance(false); continue; }
                return result;
            }
            79 => {
                result = true; lexer.set_result_symbol(anon_sym_ENTITY); lexer.mark_end();
                return result;
            }
            80 => {
                if lookahead == 79 { state = 91; lexer.advance(false); continue; }
                return result;
            }
            81 => {
                result = true; lexer.set_result_symbol(anon_sym_PUBLIC); lexer.mark_end();
                return result;
            }
            82 => {
                result = true; lexer.set_result_symbol(anon_sym_SYSTEM); lexer.mark_end();
                return result;
            }
            83 => {
                if lookahead == 110 { state = 92; lexer.advance(false); continue; }
                return result;
            }
            84 => {
                if lookahead == 108 { state = 93; lexer.advance(false); continue; }
                return result;
            }
            85 => {
                if lookahead == 110 { state = 94; lexer.advance(false); continue; }
                return result;
            }
            86 => {
                if lookahead == 100 { state = 95; lexer.advance(false); continue; }
                return result;
            }
            87 => {
                if lookahead == 121 { state = 96; lexer.advance(false); continue; }
                return result;
            }
            88 => {
                result = true; lexer.set_result_symbol(anon_sym_ATTLIST); lexer.mark_end();
                return result;
            }
            89 => {
                result = true; lexer.set_result_symbol(anon_sym_DOCTYPE); lexer.mark_end();
                return result;
            }
            90 => {
                result = true; lexer.set_result_symbol(anon_sym_ELEMENT); lexer.mark_end();
                return result;
            }
            91 => {
                if lookahead == 78 { state = 97; lexer.advance(false); continue; }
                return result;
            }
            92 => {
                if lookahead == 103 { state = 98; lexer.advance(false); continue; }
                return result;
            }
            93 => {
                if lookahead == 111 { state = 99; lexer.advance(false); continue; }
                return result;
            }
            94 => {
                result = true; lexer.set_result_symbol(anon_sym_version); lexer.mark_end();
                return result;
            }
            95 => {
                if lookahead == 101 { state = 100; lexer.advance(false); continue; }
                return result;
            }
            96 => {
                if lookahead == 108 { state = 101; lexer.advance(false); continue; }
                return result;
            }
            97 => {
                result = true; lexer.set_result_symbol(anon_sym_NOTATION); lexer.mark_end();
                return result;
            }
            98 => {
                result = true; lexer.set_result_symbol(anon_sym_encoding); lexer.mark_end();
                return result;
            }
            99 => {
                if lookahead == 110 { state = 102; lexer.advance(false); continue; }
                return result;
            }
            100 => {
                if lookahead == 108 { state = 103; lexer.advance(false); continue; }
                return result;
            }
            101 => {
                if lookahead == 101 { state = 104; lexer.advance(false); continue; }
                return result;
            }
            102 => {
                if lookahead == 101 { state = 105; lexer.advance(false); continue; }
                return result;
            }
            103 => {
                result = true; lexer.set_result_symbol(anon_sym_xml_DASHmodel); lexer.mark_end();
                return result;
            }
            104 => {
                if lookahead == 115 { state = 106; lexer.advance(false); continue; }
                return result;
            }
            105 => {
                result = true; lexer.set_result_symbol(anon_sym_standalone); lexer.mark_end();
                return result;
            }
            106 => {
                if lookahead == 104 { state = 107; lexer.advance(false); continue; }
                return result;
            }
            107 => {
                if lookahead == 101 { state = 108; lexer.advance(false); continue; }
                return result;
            }
            108 => {
                if lookahead == 101 { state = 109; lexer.advance(false); continue; }
                return result;
            }
            109 => {
                if lookahead == 116 { state = 110; lexer.advance(false); continue; }
                return result;
            }
            110 => {
                result = true; lexer.set_result_symbol(anon_sym_xml_DASHstylesheet); lexer.mark_end();
                return result;
            }
            _ => return false,
        }
    }
}
