[workspace]
resolver = "3"
members = [
    "tables",
    "runtime",
    "grammars/bash",
    "grammars/c",
    "grammars/c_sharp",
    "grammars/cmake",
    "grammars/cpp",
    "grammars/css",
    "grammars/cuda",
    "grammars/dart",
    "grammars/dtd",
    "grammars/elixir",
    "grammars/elm",
    "grammars/embedded_template",
    "grammars/erlang",
    "grammars/fortran",
    "grammars/fsharp",
    "grammars/glsl",
    "grammars/go",
    "grammars/haskell",
    "grammars/hcl",
    "grammars/html",
    "grammars/java",
    "grammars/javascript",
    "grammars/json",
    "grammars/julia",
    "grammars/kotlin",
    "grammars/lua",
    "grammars/make",
    "grammars/markdown",
    "grammars/markdown_inline",
    "grammars/objc",
    "grammars/ocaml",
    "grammars/ocaml_interface",
    "grammars/odin",
    "grammars/perl",
    "grammars/php",
    "grammars/php_only",
    "grammars/powershell",
    "grammars/proto",
    "grammars/python",
    "grammars/r",
    "grammars/ruby",
    "grammars/rust",
    "grammars/scala",
    "grammars/solidity",
    "grammars/sql",
    "grammars/svelte",
    "grammars/swift",
    "grammars/toml",
    "grammars/tsx",
    "grammars/typescript",
    "grammars/verilog",
    "grammars/xml",
    "grammars/yaml",
    "grammars/zig",
]

[profile.release]
debug = "line-tables-only"
