# Written by the ts_port host; agents don't change it.
[workspace]
resolver = "3"
members = [
    "tables",
    "runtime",
    "grammars/bash",
    "grammars/c",
    "grammars/c_sharp",
    "grammars/cpp",
    "grammars/css",
    "grammars/go",
    "grammars/html",
    "grammars/java",
    "grammars/javascript",
    "grammars/json",
    "grammars/kotlin",
    "grammars/lua",
    "grammars/markdown",
    "grammars/markdown_inline",
    "grammars/php",
    "grammars/php_only",
    "grammars/python",
    "grammars/ruby",
    "grammars/rust",
    "grammars/swift",
    "grammars/toml",
    "grammars/tsx",
    "grammars/typescript",
    "grammars/yaml",
    "grammars/zig",
]

[profile.release]
debug = "line-tables-only"
