//! The `css` tree-sitter grammar for the ported runtime: its tables (decoded from
//! `tables.bin`) and lexer (`lex.rs`), converted from the grammar's `src/parser.c`.
//!
//! GENERATED BY THE TS_PORT HOST. DO NOT EDIT (only `scanner.rs` is hand-written).

mod lex;
mod scanner;

use std::sync::LazyLock;

use ts_port_tables::{LanguageTables, LexFn, ScannerCreateFn};

/// The grammar's tables, written by the host from the compiled C grammar.
static BLOB: &[u8] = include_bytes!("tables.bin");

static LANGUAGE: LazyLock<LanguageTables> = LazyLock::new(decode);

/// The grammar's tables (the C `tree_sitter_css()`), decoded on first use.
pub fn language() -> &'static LanguageTables {
    &LANGUAGE
}

fn decode() -> LanguageTables {
    let keyword_lex_fn: Option<LexFn> = None;
    let scanner_create: Option<ScannerCreateFn> = Some(scanner::create);
    LanguageTables::decode(BLOB, lex::ts_lex, keyword_lex_fn, scanner_create)
}

#[cfg(test)]
mod tests {
    #[test]
    fn tables_decode() {
        let language = super::language();
        assert_eq!(language.abi_version, 15);
        assert_eq!(language.state_count, 442);
        assert_eq!(language.symbol_count, 142);
    }
}
