//! The `json` grammar's lexer: `ts_lex`, transliterated from
//! its `src/parser.c`, with the symbols and character sets they use.
//!
//! GENERATED BY THE TS_PORT HOST. DO NOT EDIT.
//!
//! Each C `case` is a `match` arm, run once per character: `ADVANCE(n)` and
//! `SKIP(n)` set the state, call `lexer.advance(skip)` and start the next round
//! (C's `goto next_state`), `ACCEPT_TOKEN` sets the result and marks the end, and
//! `END_STATE()` returns the result.
#![allow(non_upper_case_globals, unreachable_code, clippy::all)]

use ts_port_tables::{Lexer, StateId, Symbol};

const anon_sym_COLON: Symbol = 4;
const anon_sym_COMMA: Symbol = 2;
const anon_sym_DQUOTE: Symbol = 7;
const anon_sym_LBRACE: Symbol = 1;
const anon_sym_LBRACK: Symbol = 5;
const anon_sym_RBRACE: Symbol = 3;
const anon_sym_RBRACK: Symbol = 6;
const sym_comment: Symbol = 14;
const sym_escape_sequence: Symbol = 9;
const sym_false: Symbol = 12;
const sym_null: Symbol = 13;
const sym_number: Symbol = 10;
const sym_string_content: Symbol = 8;
const sym_true: Symbol = 11;
const ts_builtin_sym_end: Symbol = 0;

/// `ADVANCE_MAP`: the state paired with the first key equal to `lookahead`.
fn advance_map(map: &[(u16, StateId)], lookahead: i32) -> Option<StateId> {
    map.iter()
        .find(|&&(key, _)| i32::from(key) == lookahead)
        .map(|&(_, state)| state)
}

/// C's `ts_lex`: lexes one token from lex state `state`; returns whether it
/// accepted one.
#[rustfmt::skip]
pub(crate) fn ts_lex(lexer: &mut dyn Lexer, mut state: StateId) -> bool {
    let mut result = false;
    loop {
        // C's `start:` label (reached again after each `next_state:` advance).
        let lookahead = lexer.lookahead();
        let eof = lexer.eof();
        match state {
            0 => {
                if eof { state = 21; lexer.advance(false); continue; }
                if let Some(next) = advance_map(&[
                    (34, 28), (44, 23), (45, 7), (47, 3), (48, 35), (58, 25), (91, 26), (92, 18),
                    (93, 27), (102, 8), (110, 17), (116, 14), (123, 22), (125, 24),
                ], lookahead) { state = next; lexer.advance(false); continue; }
                if 9 <= lookahead && lookahead <= 13 || lookahead == 32 { state = 20; lexer.advance(true); continue; }
                if 49 <= lookahead && lookahead <= 57 { state = 36; lexer.advance(false); continue; }
                return result;
            }
            1 => {
                if lookahead == 10 { state = 2; lexer.advance(true); continue; }
                if lookahead == 34 { state = 28; lexer.advance(false); continue; }
                if lookahead == 47 { state = 29; lexer.advance(false); continue; }
                if lookahead == 92 { state = 18; lexer.advance(false); continue; }
                if 9 <= lookahead && lookahead <= 13 || lookahead == 32 { state = 32; lexer.advance(false); continue; }
                if lookahead != 0 { state = 33; lexer.advance(false); continue; }
                return result;
            }
            2 => {
                if lookahead == 34 { state = 28; lexer.advance(false); continue; }
                if lookahead == 47 { state = 3; lexer.advance(false); continue; }
                if 9 <= lookahead && lookahead <= 13 || lookahead == 32 { state = 2; lexer.advance(true); continue; }
                return result;
            }
            3 => {
                if lookahead == 42 { state = 5; lexer.advance(false); continue; }
                if lookahead == 47 { state = 43; lexer.advance(false); continue; }
                return result;
            }
            4 => {
                if lookahead == 42 { state = 4; lexer.advance(false); continue; }
                if lookahead == 47 { state = 42; lexer.advance(false); continue; }
                if lookahead != 0 { state = 5; lexer.advance(false); continue; }
                return result;
            }
            5 => {
                if lookahead == 42 { state = 4; lexer.advance(false); continue; }
                if lookahead != 0 { state = 5; lexer.advance(false); continue; }
                return result;
            }
            6 => {
                if lookahead == 45 { state = 19; lexer.advance(false); continue; }
                if 48 <= lookahead && lookahead <= 57 { state = 38; lexer.advance(false); continue; }
                return result;
            }
            7 => {
                if lookahead == 48 { state = 35; lexer.advance(false); continue; }
                if 49 <= lookahead && lookahead <= 57 { state = 36; lexer.advance(false); continue; }
                return result;
            }
            8 => {
                if lookahead == 97 { state = 11; lexer.advance(false); continue; }
                return result;
            }
            9 => {
                if lookahead == 101 { state = 39; lexer.advance(false); continue; }
                return result;
            }
            10 => {
                if lookahead == 101 { state = 40; lexer.advance(false); continue; }
                return result;
            }
            11 => {
                if lookahead == 108 { state = 15; lexer.advance(false); continue; }
                return result;
            }
            12 => {
                if lookahead == 108 { state = 41; lexer.advance(false); continue; }
                return result;
            }
            13 => {
                if lookahead == 108 { state = 12; lexer.advance(false); continue; }
                return result;
            }
            14 => {
                if lookahead == 114 { state = 16; lexer.advance(false); continue; }
                return result;
            }
            15 => {
                if lookahead == 115 { state = 10; lexer.advance(false); continue; }
                return result;
            }
            16 => {
                if lookahead == 117 { state = 9; lexer.advance(false); continue; }
                return result;
            }
            17 => {
                if lookahead == 117 { state = 13; lexer.advance(false); continue; }
                return result;
            }
            18 => {
                if let Some(next) = advance_map(&[
                    (34, 34), (47, 34), (92, 34), (98, 34), (102, 34), (110, 34), (114, 34), (116, 34),
                    (117, 34),
                ], lookahead) { state = next; lexer.advance(false); continue; }
                return result;
            }
            19 => {
                if 48 <= lookahead && lookahead <= 57 { state = 38; lexer.advance(false); continue; }
                return result;
            }
            20 => {
                if eof { state = 21; lexer.advance(false); continue; }
                if let Some(next) = advance_map(&[
                    (34, 28), (44, 23), (45, 7), (47, 3), (48, 35), (58, 25), (91, 26), (93, 27),
                    (102, 8), (110, 17), (116, 14), (123, 22), (125, 24),
                ], lookahead) { state = next; lexer.advance(false); continue; }
                if 9 <= lookahead && lookahead <= 13 || lookahead == 32 { state = 20; lexer.advance(true); continue; }
                if 49 <= lookahead && lookahead <= 57 { state = 36; lexer.advance(false); continue; }
                return result;
            }
            21 => {
                result = true; lexer.set_result_symbol(ts_builtin_sym_end); lexer.mark_end();
                return result;
            }
            22 => {
                result = true; lexer.set_result_symbol(anon_sym_LBRACE); lexer.mark_end();
                return result;
            }
            23 => {
                result = true; lexer.set_result_symbol(anon_sym_COMMA); lexer.mark_end();
                return result;
            }
            24 => {
                result = true; lexer.set_result_symbol(anon_sym_RBRACE); lexer.mark_end();
                return result;
            }
            25 => {
                result = true; lexer.set_result_symbol(anon_sym_COLON); lexer.mark_end();
                return result;
            }
            26 => {
                result = true; lexer.set_result_symbol(anon_sym_LBRACK); lexer.mark_end();
                return result;
            }
            27 => {
                result = true; lexer.set_result_symbol(anon_sym_RBRACK); lexer.mark_end();
                return result;
            }
            28 => {
                result = true; lexer.set_result_symbol(anon_sym_DQUOTE); lexer.mark_end();
                return result;
            }
            29 => {
                result = true; lexer.set_result_symbol(sym_string_content); lexer.mark_end();
                if lookahead == 42 { state = 31; lexer.advance(false); continue; }
                if lookahead == 47 { state = 33; lexer.advance(false); continue; }
                if lookahead != 0 && lookahead != 10 && lookahead != 34 && lookahead != 92 { state = 33; lexer.advance(false); continue; }
                return result;
            }
            30 => {
                result = true; lexer.set_result_symbol(sym_string_content); lexer.mark_end();
                if lookahead == 42 { state = 30; lexer.advance(false); continue; }
                if lookahead == 47 { state = 33; lexer.advance(false); continue; }
                if lookahead != 0 && lookahead != 10 && lookahead != 34 && lookahead != 92 { state = 31; lexer.advance(false); continue; }
                return result;
            }
            31 => {
                result = true; lexer.set_result_symbol(sym_string_content); lexer.mark_end();
                if lookahead == 42 { state = 30; lexer.advance(false); continue; }
                if lookahead != 0 && lookahead != 10 && lookahead != 34 && lookahead != 92 { state = 31; lexer.advance(false); continue; }
                return result;
            }
            32 => {
                result = true; lexer.set_result_symbol(sym_string_content); lexer.mark_end();
                if lookahead == 47 { state = 29; lexer.advance(false); continue; }
                if lookahead == 9 || 11 <= lookahead && lookahead <= 13 || lookahead == 32 { state = 32; lexer.advance(false); continue; }
                if lookahead != 0 && (lookahead < 9 || 13 < lookahead) && lookahead != 34 && lookahead != 92 { state = 33; lexer.advance(false); continue; }
                return result;
            }
            33 => {
                result = true; lexer.set_result_symbol(sym_string_content); lexer.mark_end();
                if lookahead != 0 && lookahead != 10 && lookahead != 34 && lookahead != 92 { state = 33; lexer.advance(false); continue; }
                return result;
            }
            34 => {
                result = true; lexer.set_result_symbol(sym_escape_sequence); lexer.mark_end();
                return result;
            }
            35 => {
                result = true; lexer.set_result_symbol(sym_number); lexer.mark_end();
                if lookahead == 46 { state = 37; lexer.advance(false); continue; }
                if lookahead == 69 || lookahead == 101 { state = 6; lexer.advance(false); continue; }
                return result;
            }
            36 => {
                result = true; lexer.set_result_symbol(sym_number); lexer.mark_end();
                if lookahead == 46 { state = 37; lexer.advance(false); continue; }
                if lookahead == 69 || lookahead == 101 { state = 6; lexer.advance(false); continue; }
                if 48 <= lookahead && lookahead <= 57 { state = 36; lexer.advance(false); continue; }
                return result;
            }
            37 => {
                result = true; lexer.set_result_symbol(sym_number); lexer.mark_end();
                if lookahead == 69 || lookahead == 101 { state = 6; lexer.advance(false); continue; }
                if 48 <= lookahead && lookahead <= 57 { state = 37; lexer.advance(false); continue; }
                return result;
            }
            38 => {
                result = true; lexer.set_result_symbol(sym_number); lexer.mark_end();
                if 48 <= lookahead && lookahead <= 57 { state = 38; lexer.advance(false); continue; }
                return result;
            }
            39 => {
                result = true; lexer.set_result_symbol(sym_true); lexer.mark_end();
                return result;
            }
            40 => {
                result = true; lexer.set_result_symbol(sym_false); lexer.mark_end();
                return result;
            }
            41 => {
                result = true; lexer.set_result_symbol(sym_null); lexer.mark_end();
                return result;
            }
            42 => {
                result = true; lexer.set_result_symbol(sym_comment); lexer.mark_end();
                return result;
            }
            43 => {
                result = true; lexer.set_result_symbol(sym_comment); lexer.mark_end();
                if lookahead != 0 && lookahead != 10 { state = 43; lexer.advance(false); continue; }
                return result;
            }
            _ => return false,
        }
    }
}
