[package]
name = "mhr_tree_sitter_elm"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false
description = "The Elm grammar for mhr_tree_sitter (pure-Rust tree-sitter), from tree-sitter-elm 5.9.4"

[lib]
name = "tree_sitter_elm"

[dependencies]
mhr_tree_sitter_language = { path = "../../tables" }

[dev-dependencies]
mhr_tree_sitter = { path = "../../runtime" }
