//! The `svelte` grammar's lexer: `ts_lex`, transliterated from
//! its `src/parser.c`, with the symbols and character sets they use.
//!
//! GENERATED BY THE TS_PORT HOST. DO NOT EDIT.
//!
//! Each C `case` is a `match` arm, run once per character: `ADVANCE(n)` and
//! `SKIP(n)` set the state, call `lexer.advance(skip)` and start the next round
//! (C's `goto next_state`), `ACCEPT_TOKEN` sets the result and marks the end, and
//! `END_STATE()` returns the result.
#![allow(non_upper_case_globals, unreachable_code, clippy::all)]

use ts_port_tables::{CharacterRange, Lexer, StateId, Symbol, set_contains};

const anon_sym_AT: Symbol = 36;
const anon_sym_COLON: Symbol = 21;
const anon_sym_DQUOTE: Symbol = 13;
const anon_sym_EQ: Symbol = 8;
const anon_sym_GT: Symbol = 3;
const anon_sym_LBRACE: Symbol = 19;
const anon_sym_LPAREN: Symbol = 33;
const anon_sym_LT: Symbol = 5;
const anon_sym_LT_BANG: Symbol = 1;
const anon_sym_LT_SLASH: Symbol = 7;
const anon_sym_POUND: Symbol = 17;
const anon_sym_RBRACE: Symbol = 20;
const anon_sym_RPAREN: Symbol = 34;
const anon_sym_SLASH: Symbol = 24;
const anon_sym_SLASH_GT: Symbol = 6;
const anon_sym_SQUOTE: Symbol = 12;
const anon_sym_as: Symbol = 26;
const anon_sym_await: Symbol = 27;
const anon_sym_catch: Symbol = 29;
const anon_sym_const: Symbol = 38;
const anon_sym_debug: Symbol = 39;
const anon_sym_each: Symbol = 25;
const anon_sym_else: Symbol = 23;
const anon_sym_elseif: Symbol = 22;
const anon_sym_html: Symbol = 37;
const anon_sym_if: Symbol = 18;
const anon_sym_key: Symbol = 30;
const anon_sym_render: Symbol = 40;
const anon_sym_snippet: Symbol = 31;
const anon_sym_then: Symbol = 28;
const aux_sym__double_quoted_attribute_value_token1: Symbol = 16;
const aux_sym__single_quoted_attribute_value_token1: Symbol = 15;
const aux_sym__tag_value_token1: Symbol = 35;
const aux_sym_doctype_token1: Symbol = 2;
const aux_sym_snippet_start_token1: Symbol = 32;
const sym__doctype: Symbol = 4;
const sym_attribute_name: Symbol = 9;
const sym_attribute_value: Symbol = 10;
const sym_entity: Symbol = 11;
const sym_text: Symbol = 14;
const ts_builtin_sym_end: Symbol = 0;

#[rustfmt::skip]
static sym_attribute_name_character_set_1: [CharacterRange; 9] = [
    CharacterRange::new(0, 8), CharacterRange::new(14, 31), CharacterRange::new(33, 33), CharacterRange::new(35, 38), CharacterRange::new(40, 46), CharacterRange::new(48, 59),
    CharacterRange::new(63, 122), CharacterRange::new(124, 124), CharacterRange::new(126, 1114111),
];

/// `ADVANCE_MAP`: the state paired with the first key equal to `lookahead`.
fn advance_map(map: &[(u16, StateId)], lookahead: i32) -> Option<StateId> {
    map.iter()
        .find(|&&(key, _)| i32::from(key) == lookahead)
        .map(|&(_, state)| state)
}

/// C's `ts_lex`: lexes one token from lex state `state`; returns whether it
/// accepted one.
#[rustfmt::skip]
pub(crate) fn ts_lex(lexer: &mut dyn Lexer, mut state: StateId) -> bool {
    let mut result = false;
    loop {
        // C's `start:` label (reached again after each `next_state:` advance).
        let lookahead = lexer.lookahead();
        let eof = lexer.eof();
        match state {
            0 => {
                if eof { state = 65; lexer.advance(false); continue; }
                if let Some(next) = advance_map(&[
                    (34, 118), (35, 124), (38, 4), (39, 117), (40, 142), (41, 143), (47, 133), (58, 128),
                    (60, 71), (61, 74), (62, 69), (64, 145), (68, 56), (97, 43), (99, 9), (100, 15),
                    (101, 8), (104, 47), (105, 24), (107, 16), (114, 21), (115, 36), (116, 29), (123, 126),
                    (125, 127),
                ], lookahead) { state = next; lexer.advance(false); continue; }
                if 9 <= lookahead && lookahead <= 13 || lookahead == 32 { state = 144; lexer.advance(false); continue; }
                return result;
            }
            1 => {
                if lookahead == 34 { state = 118; lexer.advance(false); continue; }
                if lookahead == 39 { state = 117; lexer.advance(false); continue; }
                if lookahead == 123 { state = 126; lexer.advance(false); continue; }
                if 9 <= lookahead && lookahead <= 13 || lookahead == 32 { state = 144; lexer.advance(false); continue; }
                if lookahead != 0 && (lookahead < 60 || 62 < lookahead) && lookahead != 125 { state = 76; lexer.advance(false); continue; }
                return result;
            }
            2 => {
                if lookahead == 34 { state = 118; lexer.advance(false); continue; }
                if lookahead == 123 { state = 126; lexer.advance(false); continue; }
                if 9 <= lookahead && lookahead <= 13 || lookahead == 32 { state = 122; lexer.advance(false); continue; }
                if lookahead != 0 { state = 123; lexer.advance(false); continue; }
                return result;
            }
            3 => {
                if lookahead == 35 { state = 124; lexer.advance(false); continue; }
                if lookahead == 47 { state = 132; lexer.advance(false); continue; }
                if lookahead == 58 { state = 128; lexer.advance(false); continue; }
                if lookahead == 64 { state = 145; lexer.advance(false); continue; }
                if 9 <= lookahead && lookahead <= 13 || lookahead == 32 { state = 144; lexer.advance(false); continue; }
                if lookahead == 36 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 141; lexer.advance(false); continue; }
                return result;
            }
            4 => {
                if lookahead == 35 { state = 59; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 116; lexer.advance(false); continue; }
                return result;
            }
            5 => {
                if lookahead == 39 { state = 117; lexer.advance(false); continue; }
                if lookahead == 123 { state = 126; lexer.advance(false); continue; }
                if 9 <= lookahead && lookahead <= 13 || lookahead == 32 { state = 120; lexer.advance(false); continue; }
                if lookahead != 0 { state = 121; lexer.advance(false); continue; }
                return result;
            }
            6 => {
                if lookahead == 47 { state = 7; lexer.advance(false); continue; }
                if lookahead == 61 { state = 74; lexer.advance(false); continue; }
                if lookahead == 62 { state = 69; lexer.advance(false); continue; }
                if lookahead == 123 { state = 126; lexer.advance(false); continue; }
                if 9 <= lookahead && lookahead <= 13 || lookahead == 32 { state = 144; lexer.advance(false); continue; }
                if lookahead != 0 && lookahead != 34 && lookahead != 39 && (lookahead < 60 || 62 < lookahead) && lookahead != 125 { state = 75; lexer.advance(false); continue; }
                return result;
            }
            7 => {
                if lookahead == 62 { state = 72; lexer.advance(false); continue; }
                return result;
            }
            8 => {
                if lookahead == 97 { state = 12; lexer.advance(false); continue; }
                if lookahead == 108 { state = 44; lexer.advance(false); continue; }
                return result;
            }
            9 => {
                if lookahead == 97 { state = 51; lexer.advance(false); continue; }
                if lookahead == 111 { state = 39; lexer.advance(false); continue; }
                return result;
            }
            10 => {
                if lookahead == 97 { state = 32; lexer.advance(false); continue; }
                return result;
            }
            11 => {
                if lookahead == 98 { state = 52; lexer.advance(false); continue; }
                return result;
            }
            12 => {
                if lookahead == 99 { state = 27; lexer.advance(false); continue; }
                return result;
            }
            13 => {
                if lookahead == 99 { state = 28; lexer.advance(false); continue; }
                return result;
            }
            14 => {
                if lookahead == 100 { state = 18; lexer.advance(false); continue; }
                return result;
            }
            15 => {
                if lookahead == 101 { state = 11; lexer.advance(false); continue; }
                if lookahead == 79 || lookahead == 111 { state = 54; lexer.advance(false); continue; }
                return result;
            }
            16 => {
                if lookahead == 101 { state = 53; lexer.advance(false); continue; }
                return result;
            }
            17 => {
                if lookahead == 101 { state = 131; lexer.advance(false); continue; }
                return result;
            }
            18 => {
                if lookahead == 101 { state = 42; lexer.advance(false); continue; }
                return result;
            }
            19 => {
                if lookahead == 101 { state = 130; lexer.advance(false); continue; }
                return result;
            }
            20 => {
                if lookahead == 101 { state = 34; lexer.advance(false); continue; }
                if 9 <= lookahead && lookahead <= 13 || lookahead == 32 { state = 144; lexer.advance(false); continue; }
                return result;
            }
            21 => {
                if lookahead == 101 { state = 37; lexer.advance(false); continue; }
                return result;
            }
            22 => {
                if lookahead == 101 { state = 38; lexer.advance(false); continue; }
                return result;
            }
            23 => {
                if lookahead == 101 { state = 50; lexer.advance(false); continue; }
                return result;
            }
            24 => {
                if lookahead == 102 { state = 125; lexer.advance(false); continue; }
                return result;
            }
            25 => {
                if lookahead == 102 { state = 129; lexer.advance(false); continue; }
                return result;
            }
            26 => {
                if lookahead == 103 { state = 148; lexer.advance(false); continue; }
                return result;
            }
            27 => {
                if lookahead == 104 { state = 134; lexer.advance(false); continue; }
                return result;
            }
            28 => {
                if lookahead == 104 { state = 138; lexer.advance(false); continue; }
                return result;
            }
            29 => {
                if lookahead == 104 { state = 22; lexer.advance(false); continue; }
                return result;
            }
            30 => {
                if lookahead == 105 { state = 40; lexer.advance(false); continue; }
                return result;
            }
            31 => {
                if lookahead == 105 { state = 25; lexer.advance(false); continue; }
                return result;
            }
            32 => {
                if lookahead == 105 { state = 48; lexer.advance(false); continue; }
                return result;
            }
            33 => {
                if lookahead == 108 { state = 146; lexer.advance(false); continue; }
                return result;
            }
            34 => {
                if lookahead == 108 { state = 46; lexer.advance(false); continue; }
                return result;
            }
            35 => {
                if lookahead == 109 { state = 33; lexer.advance(false); continue; }
                return result;
            }
            36 => {
                if lookahead == 110 { state = 30; lexer.advance(false); continue; }
                return result;
            }
            37 => {
                if lookahead == 110 { state = 14; lexer.advance(false); continue; }
                return result;
            }
            38 => {
                if lookahead == 110 { state = 137; lexer.advance(false); continue; }
                return result;
            }
            39 => {
                if lookahead == 110 { state = 45; lexer.advance(false); continue; }
                return result;
            }
            40 => {
                if lookahead == 112 { state = 41; lexer.advance(false); continue; }
                return result;
            }
            41 => {
                if lookahead == 112 { state = 23; lexer.advance(false); continue; }
                return result;
            }
            42 => {
                if lookahead == 114 { state = 149; lexer.advance(false); continue; }
                return result;
            }
            43 => {
                if lookahead == 115 { state = 135; lexer.advance(false); continue; }
                if lookahead == 119 { state = 10; lexer.advance(false); continue; }
                return result;
            }
            44 => {
                if lookahead == 115 { state = 17; lexer.advance(false); continue; }
                return result;
            }
            45 => {
                if lookahead == 115 { state = 49; lexer.advance(false); continue; }
                return result;
            }
            46 => {
                if lookahead == 115 { state = 19; lexer.advance(false); continue; }
                return result;
            }
            47 => {
                if lookahead == 116 { state = 35; lexer.advance(false); continue; }
                return result;
            }
            48 => {
                if lookahead == 116 { state = 136; lexer.advance(false); continue; }
                return result;
            }
            49 => {
                if lookahead == 116 { state = 147; lexer.advance(false); continue; }
                return result;
            }
            50 => {
                if lookahead == 116 { state = 140; lexer.advance(false); continue; }
                return result;
            }
            51 => {
                if lookahead == 116 { state = 13; lexer.advance(false); continue; }
                return result;
            }
            52 => {
                if lookahead == 117 { state = 26; lexer.advance(false); continue; }
                return result;
            }
            53 => {
                if lookahead == 121 { state = 139; lexer.advance(false); continue; }
                return result;
            }
            54 => {
                if lookahead == 67 || lookahead == 99 { state = 58; lexer.advance(false); continue; }
                return result;
            }
            55 => {
                if lookahead == 69 || lookahead == 101 { state = 70; lexer.advance(false); continue; }
                return result;
            }
            56 => {
                if lookahead == 79 || lookahead == 111 { state = 54; lexer.advance(false); continue; }
                return result;
            }
            57 => {
                if lookahead == 80 || lookahead == 112 { state = 55; lexer.advance(false); continue; }
                return result;
            }
            58 => {
                if lookahead == 84 || lookahead == 116 { state = 60; lexer.advance(false); continue; }
                return result;
            }
            59 => {
                if lookahead == 88 || lookahead == 120 { state = 63; lexer.advance(false); continue; }
                if 48 <= lookahead && lookahead <= 57 { state = 82; lexer.advance(false); continue; }
                return result;
            }
            60 => {
                if lookahead == 89 || lookahead == 121 { state = 57; lexer.advance(false); continue; }
                return result;
            }
            61 => {
                if 9 <= lookahead && lookahead <= 13 || lookahead == 32 { state = 61; lexer.advance(false); continue; }
                if lookahead != 0 && lookahead != 38 && lookahead != 60 && lookahead != 62 && lookahead != 123 && lookahead != 125 { state = 119; lexer.advance(false); continue; }
                return result;
            }
            62 => {
                if 9 <= lookahead && lookahead <= 13 || lookahead == 32 { state = 67; lexer.advance(false); continue; }
                if lookahead != 0 && lookahead != 62 { state = 68; lexer.advance(false); continue; }
                return result;
            }
            63 => {
                if 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 70 || 97 <= lookahead && lookahead <= 102 { state = 87; lexer.advance(false); continue; }
                return result;
            }
            64 => {
                if eof { state = 65; lexer.advance(false); continue; }
                if lookahead == 38 { state = 4; lexer.advance(false); continue; }
                if lookahead == 60 { state = 71; lexer.advance(false); continue; }
                if lookahead == 123 { state = 126; lexer.advance(false); continue; }
                if 9 <= lookahead && lookahead <= 13 || lookahead == 32 { state = 144; lexer.advance(false); continue; }
                if lookahead != 0 && lookahead != 62 && lookahead != 125 { state = 119; lexer.advance(false); continue; }
                return result;
            }
            65 => {
                result = true; lexer.set_result_symbol(ts_builtin_sym_end); lexer.mark_end();
                return result;
            }
            66 => {
                result = true; lexer.set_result_symbol(anon_sym_LT_BANG); lexer.mark_end();
                return result;
            }
            67 => {
                result = true; lexer.set_result_symbol(aux_sym_doctype_token1); lexer.mark_end();
                if 9 <= lookahead && lookahead <= 13 || lookahead == 32 { state = 67; lexer.advance(false); continue; }
                if lookahead != 0 && lookahead != 62 { state = 68; lexer.advance(false); continue; }
                return result;
            }
            68 => {
                result = true; lexer.set_result_symbol(aux_sym_doctype_token1); lexer.mark_end();
                if lookahead != 0 && lookahead != 62 { state = 68; lexer.advance(false); continue; }
                return result;
            }
            69 => {
                result = true; lexer.set_result_symbol(anon_sym_GT); lexer.mark_end();
                return result;
            }
            70 => {
                result = true; lexer.set_result_symbol(sym__doctype); lexer.mark_end();
                return result;
            }
            71 => {
                result = true; lexer.set_result_symbol(anon_sym_LT); lexer.mark_end();
                if lookahead == 33 { state = 66; lexer.advance(false); continue; }
                if lookahead == 47 { state = 73; lexer.advance(false); continue; }
                return result;
            }
            72 => {
                result = true; lexer.set_result_symbol(anon_sym_SLASH_GT); lexer.mark_end();
                return result;
            }
            73 => {
                result = true; lexer.set_result_symbol(anon_sym_LT_SLASH); lexer.mark_end();
                return result;
            }
            74 => {
                result = true; lexer.set_result_symbol(anon_sym_EQ); lexer.mark_end();
                return result;
            }
            75 => {
                result = true; lexer.set_result_symbol(sym_attribute_name); lexer.mark_end();
                if !eof && set_contains(&sym_attribute_name_character_set_1, lookahead) { state = 75; lexer.advance(false); continue; }
                return result;
            }
            76 => {
                result = true; lexer.set_result_symbol(sym_attribute_value); lexer.mark_end();
                if !eof && set_contains(&sym_attribute_name_character_set_1, lookahead) || lookahead == 47 { state = 76; lexer.advance(false); continue; }
                return result;
            }
            77 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                return result;
            }
            78 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                return result;
            }
            79 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 48 <= lookahead && lookahead <= 57 { state = 78; lexer.advance(false); continue; }
                return result;
            }
            80 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 48 <= lookahead && lookahead <= 57 { state = 79; lexer.advance(false); continue; }
                return result;
            }
            81 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 48 <= lookahead && lookahead <= 57 { state = 80; lexer.advance(false); continue; }
                return result;
            }
            82 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 48 <= lookahead && lookahead <= 57 { state = 81; lexer.advance(false); continue; }
                return result;
            }
            83 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 70 || 97 <= lookahead && lookahead <= 102 { state = 78; lexer.advance(false); continue; }
                return result;
            }
            84 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 70 || 97 <= lookahead && lookahead <= 102 { state = 83; lexer.advance(false); continue; }
                return result;
            }
            85 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 70 || 97 <= lookahead && lookahead <= 102 { state = 84; lexer.advance(false); continue; }
                return result;
            }
            86 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 70 || 97 <= lookahead && lookahead <= 102 { state = 85; lexer.advance(false); continue; }
                return result;
            }
            87 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 70 || 97 <= lookahead && lookahead <= 102 { state = 86; lexer.advance(false); continue; }
                return result;
            }
            88 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 78; lexer.advance(false); continue; }
                return result;
            }
            89 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 88; lexer.advance(false); continue; }
                return result;
            }
            90 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 89; lexer.advance(false); continue; }
                return result;
            }
            91 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 90; lexer.advance(false); continue; }
                return result;
            }
            92 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 91; lexer.advance(false); continue; }
                return result;
            }
            93 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 92; lexer.advance(false); continue; }
                return result;
            }
            94 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 93; lexer.advance(false); continue; }
                return result;
            }
            95 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 94; lexer.advance(false); continue; }
                return result;
            }
            96 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 95; lexer.advance(false); continue; }
                return result;
            }
            97 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 96; lexer.advance(false); continue; }
                return result;
            }
            98 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 97; lexer.advance(false); continue; }
                return result;
            }
            99 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 98; lexer.advance(false); continue; }
                return result;
            }
            100 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 99; lexer.advance(false); continue; }
                return result;
            }
            101 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 100; lexer.advance(false); continue; }
                return result;
            }
            102 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 101; lexer.advance(false); continue; }
                return result;
            }
            103 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 102; lexer.advance(false); continue; }
                return result;
            }
            104 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 103; lexer.advance(false); continue; }
                return result;
            }
            105 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 104; lexer.advance(false); continue; }
                return result;
            }
            106 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 105; lexer.advance(false); continue; }
                return result;
            }
            107 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 106; lexer.advance(false); continue; }
                return result;
            }
            108 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 107; lexer.advance(false); continue; }
                return result;
            }
            109 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 108; lexer.advance(false); continue; }
                return result;
            }
            110 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 109; lexer.advance(false); continue; }
                return result;
            }
            111 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 110; lexer.advance(false); continue; }
                return result;
            }
            112 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 111; lexer.advance(false); continue; }
                return result;
            }
            113 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 112; lexer.advance(false); continue; }
                return result;
            }
            114 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 113; lexer.advance(false); continue; }
                return result;
            }
            115 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 114; lexer.advance(false); continue; }
                return result;
            }
            116 => {
                result = true; lexer.set_result_symbol(sym_entity); lexer.mark_end();
                if lookahead == 59 { state = 77; lexer.advance(false); continue; }
                if 65 <= lookahead && lookahead <= 90 || 97 <= lookahead && lookahead <= 122 { state = 115; lexer.advance(false); continue; }
                return result;
            }
            117 => {
                result = true; lexer.set_result_symbol(anon_sym_SQUOTE); lexer.mark_end();
                return result;
            }
            118 => {
                result = true; lexer.set_result_symbol(anon_sym_DQUOTE); lexer.mark_end();
                return result;
            }
            119 => {
                result = true; lexer.set_result_symbol(sym_text); lexer.mark_end();
                if 9 <= lookahead && lookahead <= 13 || lookahead == 32 { state = 61; lexer.advance(false); continue; }
                if lookahead != 0 && lookahead != 38 && lookahead != 60 && lookahead != 62 && lookahead != 123 && lookahead != 125 { state = 119; lexer.advance(false); continue; }
                return result;
            }
            120 => {
                result = true; lexer.set_result_symbol(aux_sym__single_quoted_attribute_value_token1); lexer.mark_end();
                if 9 <= lookahead && lookahead <= 13 || lookahead == 32 { state = 120; lexer.advance(false); continue; }
                if lookahead != 0 && lookahead != 39 && lookahead != 123 { state = 121; lexer.advance(false); continue; }
                return result;
            }
            121 => {
                result = true; lexer.set_result_symbol(aux_sym__single_quoted_attribute_value_token1); lexer.mark_end();
                if lookahead != 0 && lookahead != 39 && lookahead != 123 { state = 121; lexer.advance(false); continue; }
                return result;
            }
            122 => {
                result = true; lexer.set_result_symbol(aux_sym__double_quoted_attribute_value_token1); lexer.mark_end();
                if 9 <= lookahead && lookahead <= 13 || lookahead == 32 { state = 122; lexer.advance(false); continue; }
                if lookahead != 0 && lookahead != 34 && lookahead != 123 { state = 123; lexer.advance(false); continue; }
                return result;
            }
            123 => {
                result = true; lexer.set_result_symbol(aux_sym__double_quoted_attribute_value_token1); lexer.mark_end();
                if lookahead != 0 && lookahead != 34 && lookahead != 123 { state = 123; lexer.advance(false); continue; }
                return result;
            }
            124 => {
                result = true; lexer.set_result_symbol(anon_sym_POUND); lexer.mark_end();
                return result;
            }
            125 => {
                result = true; lexer.set_result_symbol(anon_sym_if); lexer.mark_end();
                return result;
            }
            126 => {
                result = true; lexer.set_result_symbol(anon_sym_LBRACE); lexer.mark_end();
                return result;
            }
            127 => {
                result = true; lexer.set_result_symbol(anon_sym_RBRACE); lexer.mark_end();
                return result;
            }
            128 => {
                result = true; lexer.set_result_symbol(anon_sym_COLON); lexer.mark_end();
                return result;
            }
            129 => {
                result = true; lexer.set_result_symbol(anon_sym_elseif); lexer.mark_end();
                return result;
            }
            130 => {
                result = true; lexer.set_result_symbol(anon_sym_else); lexer.mark_end();
                return result;
            }
            131 => {
                result = true; lexer.set_result_symbol(anon_sym_else); lexer.mark_end();
                if lookahead == 32 { state = 31; lexer.advance(false); continue; }
                return result;
            }
            132 => {
                result = true; lexer.set_result_symbol(anon_sym_SLASH); lexer.mark_end();
                return result;
            }
            133 => {
                result = true; lexer.set_result_symbol(anon_sym_SLASH); lexer.mark_end();
                if lookahead == 62 { state = 72; lexer.advance(false); continue; }
                return result;
            }
            134 => {
                result = true; lexer.set_result_symbol(anon_sym_each); lexer.mark_end();
                return result;
            }
            135 => {
                result = true; lexer.set_result_symbol(anon_sym_as); lexer.mark_end();
                return result;
            }
            136 => {
                result = true; lexer.set_result_symbol(anon_sym_await); lexer.mark_end();
                return result;
            }
            137 => {
                result = true; lexer.set_result_symbol(anon_sym_then); lexer.mark_end();
                return result;
            }
            138 => {
                result = true; lexer.set_result_symbol(anon_sym_catch); lexer.mark_end();
                return result;
            }
            139 => {
                result = true; lexer.set_result_symbol(anon_sym_key); lexer.mark_end();
                return result;
            }
            140 => {
                result = true; lexer.set_result_symbol(anon_sym_snippet); lexer.mark_end();
                return result;
            }
            141 => {
                result = true; lexer.set_result_symbol(aux_sym_snippet_start_token1); lexer.mark_end();
                if 48 <= lookahead && lookahead <= 57 || 65 <= lookahead && lookahead <= 90 || lookahead == 95 || 97 <= lookahead && lookahead <= 122 { state = 141; lexer.advance(false); continue; }
                return result;
            }
            142 => {
                result = true; lexer.set_result_symbol(anon_sym_LPAREN); lexer.mark_end();
                return result;
            }
            143 => {
                result = true; lexer.set_result_symbol(anon_sym_RPAREN); lexer.mark_end();
                return result;
            }
            144 => {
                result = true; lexer.set_result_symbol(aux_sym__tag_value_token1); lexer.mark_end();
                if 9 <= lookahead && lookahead <= 13 || lookahead == 32 { state = 144; lexer.advance(false); continue; }
                return result;
            }
            145 => {
                result = true; lexer.set_result_symbol(anon_sym_AT); lexer.mark_end();
                return result;
            }
            146 => {
                result = true; lexer.set_result_symbol(anon_sym_html); lexer.mark_end();
                return result;
            }
            147 => {
                result = true; lexer.set_result_symbol(anon_sym_const); lexer.mark_end();
                return result;
            }
            148 => {
                result = true; lexer.set_result_symbol(anon_sym_debug); lexer.mark_end();
                return result;
            }
            149 => {
                result = true; lexer.set_result_symbol(anon_sym_render); lexer.mark_end();
                return result;
            }
            _ => return false,
        }
    }
}
