//! The `embedded_template` grammar's lexer: `ts_lex`, transliterated from
//! its `src/parser.c`, with the symbols and character sets they use.
//!
//! GENERATED BY THE TS_PORT HOST. DO NOT EDIT.
//!
//! Each C `case` is a `match` arm, run once per character: `ADVANCE(n)` and
//! `SKIP(n)` set the state, call `lexer.advance(skip)` and start the next round
//! (C's `goto next_state`), `ACCEPT_TOKEN` sets the result and marks the end, and
//! `END_STATE()` returns the result.
#![allow(non_upper_case_globals, unreachable_code, clippy::all)]

use ts_port_tables::{Lexer, StateId, Symbol};

const anon_sym_DASH_PERCENT_GT: Symbol = 10;
const anon_sym_EQ_PERCENT_GT: Symbol = 17;
const anon_sym_LT_PERCENT: Symbol = 5;
const anon_sym_LT_PERCENT_: Symbol = 6;
const anon_sym_LT_PERCENT_DASH: Symbol = 16;
const anon_sym_LT_PERCENT_EQ: Symbol = 12;
const anon_sym_LT_PERCENT_EQ_EQ: Symbol = 13;
const anon_sym_LT_PERCENT_PERCENT: Symbol = 4;
const anon_sym_LT_PERCENT_PIPE: Symbol = 7;
const anon_sym_LT_PERCENT_PIPE_EQ: Symbol = 14;
const anon_sym_LT_PERCENT_PIPE_EQ_EQ: Symbol = 15;
const anon_sym_LT_PERCENT_POUND: Symbol = 18;
const anon_sym_LT_PERCENT_TILDE: Symbol = 8;
const anon_sym_LT_PERCENTgraphql: Symbol = 19;
const anon_sym_PERCENT_GT: Symbol = 9;
const anon_sym_PERCENT_PERCENT_GT: Symbol = 2;
const anon_sym__PERCENT_GT: Symbol = 11;
const aux_sym_code_token1: Symbol = 1;
const aux_sym_content_token1: Symbol = 3;
const ts_builtin_sym_end: Symbol = 0;

/// `ADVANCE_MAP`: the state paired with the first key equal to `lookahead`.
fn advance_map(map: &[(u16, StateId)], lookahead: i32) -> Option<StateId> {
    map.iter()
        .find(|&&(key, _)| i32::from(key) == lookahead)
        .map(|&(_, state)| state)
}

/// C's `ts_lex`: lexes one token from lex state `state`; returns whether it
/// accepted one.
#[rustfmt::skip]
pub(crate) fn ts_lex(lexer: &mut dyn Lexer, mut state: StateId) -> bool {
    let mut result = false;
    loop {
        // C's `start:` label (reached again after each `next_state:` advance).
        let lookahead = lexer.lookahead();
        let eof = lexer.eof();
        match state {
            0 => {
                if eof { state = 15; lexer.advance(false); continue; }
                if lookahead == 37 { state = 17; lexer.advance(false); continue; }
                if lookahead == 45 { state = 18; lexer.advance(false); continue; }
                if lookahead == 61 { state = 19; lexer.advance(false); continue; }
                if lookahead == 95 { state = 20; lexer.advance(false); continue; }
                if lookahead != 0 { state = 21; lexer.advance(false); continue; }
                return result;
            }
            1 => {
                if lookahead == 37 { state = 17; lexer.advance(false); continue; }
                if lookahead == 45 { state = 18; lexer.advance(false); continue; }
                if lookahead == 61 { state = 16; lexer.advance(false); continue; }
                if lookahead == 95 { state = 20; lexer.advance(false); continue; }
                if lookahead != 0 { state = 21; lexer.advance(false); continue; }
                return result;
            }
            2 => {
                if lookahead == 37 { state = 17; lexer.advance(false); continue; }
                if lookahead == 45 { state = 18; lexer.advance(false); continue; }
                if lookahead == 61 { state = 19; lexer.advance(false); continue; }
                if lookahead == 95 { state = 16; lexer.advance(false); continue; }
                if lookahead != 0 { state = 21; lexer.advance(false); continue; }
                return result;
            }
            3 => {
                if lookahead == 37 { state = 17; lexer.advance(false); continue; }
                if lookahead == 45 || lookahead == 61 || lookahead == 95 { state = 16; lexer.advance(false); continue; }
                if lookahead != 0 { state = 21; lexer.advance(false); continue; }
                return result;
            }
            4 => {
                if lookahead == 62 { state = 22; lexer.advance(false); continue; }
                return result;
            }
            5 => {
                if lookahead == 62 { state = 31; lexer.advance(false); continue; }
                return result;
            }
            6 => {
                if lookahead == 62 { state = 38; lexer.advance(false); continue; }
                return result;
            }
            7 => {
                if lookahead == 62 { state = 32; lexer.advance(false); continue; }
                return result;
            }
            8 => {
                if lookahead == 97 { state = 11; lexer.advance(false); continue; }
                return result;
            }
            9 => {
                if lookahead == 104 { state = 12; lexer.advance(false); continue; }
                return result;
            }
            10 => {
                if lookahead == 108 { state = 40; lexer.advance(false); continue; }
                return result;
            }
            11 => {
                if lookahead == 112 { state = 9; lexer.advance(false); continue; }
                return result;
            }
            12 => {
                if lookahead == 113 { state = 10; lexer.advance(false); continue; }
                return result;
            }
            13 => {
                if lookahead == 114 { state = 8; lexer.advance(false); continue; }
                return result;
            }
            14 => {
                if eof { state = 15; lexer.advance(false); continue; }
                if lookahead == 60 { state = 23; lexer.advance(false); continue; }
                if lookahead != 0 { state = 24; lexer.advance(false); continue; }
                return result;
            }
            15 => {
                result = true; lexer.set_result_symbol(ts_builtin_sym_end); lexer.mark_end();
                return result;
            }
            16 => {
                result = true; lexer.set_result_symbol(aux_sym_code_token1); lexer.mark_end();
                return result;
            }
            17 => {
                result = true; lexer.set_result_symbol(aux_sym_code_token1); lexer.mark_end();
                if lookahead == 37 { state = 4; lexer.advance(false); continue; }
                if lookahead == 62 { state = 30; lexer.advance(false); continue; }
                return result;
            }
            18 => {
                result = true; lexer.set_result_symbol(aux_sym_code_token1); lexer.mark_end();
                if lookahead == 37 { state = 5; lexer.advance(false); continue; }
                return result;
            }
            19 => {
                result = true; lexer.set_result_symbol(aux_sym_code_token1); lexer.mark_end();
                if lookahead == 37 { state = 6; lexer.advance(false); continue; }
                return result;
            }
            20 => {
                result = true; lexer.set_result_symbol(aux_sym_code_token1); lexer.mark_end();
                if lookahead == 37 { state = 7; lexer.advance(false); continue; }
                return result;
            }
            21 => {
                result = true; lexer.set_result_symbol(aux_sym_code_token1); lexer.mark_end();
                if lookahead != 0 && lookahead != 37 && lookahead != 45 && lookahead != 61 && lookahead != 95 { state = 21; lexer.advance(false); continue; }
                return result;
            }
            22 => {
                result = true; lexer.set_result_symbol(anon_sym_PERCENT_PERCENT_GT); lexer.mark_end();
                return result;
            }
            23 => {
                result = true; lexer.set_result_symbol(aux_sym_content_token1); lexer.mark_end();
                if lookahead == 37 { state = 26; lexer.advance(false); continue; }
                return result;
            }
            24 => {
                result = true; lexer.set_result_symbol(aux_sym_content_token1); lexer.mark_end();
                if lookahead != 0 && lookahead != 60 { state = 24; lexer.advance(false); continue; }
                return result;
            }
            25 => {
                result = true; lexer.set_result_symbol(anon_sym_LT_PERCENT_PERCENT); lexer.mark_end();
                return result;
            }
            26 => {
                result = true; lexer.set_result_symbol(anon_sym_LT_PERCENT); lexer.mark_end();
                if let Some(next) = advance_map(&[
                    (35, 39), (37, 25), (45, 37), (61, 33), (95, 27), (103, 13), (124, 28), (126, 29),
                ], lookahead) { state = next; lexer.advance(false); continue; }
                return result;
            }
            27 => {
                result = true; lexer.set_result_symbol(anon_sym_LT_PERCENT_); lexer.mark_end();
                return result;
            }
            28 => {
                result = true; lexer.set_result_symbol(anon_sym_LT_PERCENT_PIPE); lexer.mark_end();
                if lookahead == 61 { state = 35; lexer.advance(false); continue; }
                return result;
            }
            29 => {
                result = true; lexer.set_result_symbol(anon_sym_LT_PERCENT_TILDE); lexer.mark_end();
                return result;
            }
            30 => {
                result = true; lexer.set_result_symbol(anon_sym_PERCENT_GT); lexer.mark_end();
                return result;
            }
            31 => {
                result = true; lexer.set_result_symbol(anon_sym_DASH_PERCENT_GT); lexer.mark_end();
                return result;
            }
            32 => {
                result = true; lexer.set_result_symbol(anon_sym__PERCENT_GT); lexer.mark_end();
                return result;
            }
            33 => {
                result = true; lexer.set_result_symbol(anon_sym_LT_PERCENT_EQ); lexer.mark_end();
                if lookahead == 61 { state = 34; lexer.advance(false); continue; }
                return result;
            }
            34 => {
                result = true; lexer.set_result_symbol(anon_sym_LT_PERCENT_EQ_EQ); lexer.mark_end();
                return result;
            }
            35 => {
                result = true; lexer.set_result_symbol(anon_sym_LT_PERCENT_PIPE_EQ); lexer.mark_end();
                if lookahead == 61 { state = 36; lexer.advance(false); continue; }
                return result;
            }
            36 => {
                result = true; lexer.set_result_symbol(anon_sym_LT_PERCENT_PIPE_EQ_EQ); lexer.mark_end();
                return result;
            }
            37 => {
                result = true; lexer.set_result_symbol(anon_sym_LT_PERCENT_DASH); lexer.mark_end();
                return result;
            }
            38 => {
                result = true; lexer.set_result_symbol(anon_sym_EQ_PERCENT_GT); lexer.mark_end();
                return result;
            }
            39 => {
                result = true; lexer.set_result_symbol(anon_sym_LT_PERCENT_POUND); lexer.mark_end();
                return result;
            }
            40 => {
                result = true; lexer.set_result_symbol(anon_sym_LT_PERCENTgraphql); lexer.mark_end();
                return result;
            }
            _ => return false,
        }
    }
}
