//! The `yaml` grammar's lexer: `ts_lex`, transliterated from
//! its `src/parser.c`, with the symbols and character sets they use.
//!
//! GENERATED BY THE TS_PORT HOST. DO NOT EDIT.
//!
//! Each C `case` is a `match` arm, run once per character: `ADVANCE(n)` and
//! `SKIP(n)` set the state, call `lexer.advance(skip)` and start the next round
//! (C's `goto next_state`), `ACCEPT_TOKEN` sets the result and marks the end, and
//! `END_STATE()` returns the result.
#![allow(non_upper_case_globals, unreachable_code, clippy::all)]

use ts_port_tables::{Lexer, StateId, Symbol};

const ts_builtin_sym_end: Symbol = 0;

/// C's `ts_lex`: lexes one token from lex state `state`; returns whether it
/// accepted one.
#[rustfmt::skip]
pub(crate) fn ts_lex(lexer: &mut dyn Lexer, mut state: StateId) -> bool {
    let mut result = false;
    loop {
        // C's `start:` label (reached again after each `next_state:` advance).
        let _lookahead = lexer.lookahead();
        let eof = lexer.eof();
        match state {
            0 => {
                result = true; lexer.set_result_symbol(ts_builtin_sym_end); lexer.mark_end();
                if eof { state = 1; lexer.advance(false); continue; }
                return result;
            }
            1 => {
                result = true; lexer.set_result_symbol(ts_builtin_sym_end); lexer.mark_end();
                return result;
            }
            _ => return false,
        }
    }
}
