//! `ts_port_tables`: the plain-data tables of a tree-sitter grammar, in the shape the
//! ported runtime reads them.
//!
//! GENERATED BY THE TS_PORT HOST. DO NOT EDIT: the host rewrites this file, and the
//! grammar crates (`ts_port_<key>`) decode their table blobs with it.
//!
//! Each item mirrors a part of tree-sitter's `parser.h` (v0.25.10, ABI 15) so runtime C
//! code can be translated one to one:
//!
//! | C (`parser.h`)                   | Rust                                          |
//! |----------------------------------|-----------------------------------------------|
//! | `TSSymbol`, `TSStateId`, `TSFieldId` | [`Symbol`], [`StateId`], [`FieldId`]      |
//! | `TSSymbolMetadata`               | [`SymbolMetadata`]                            |
//! | `TSMapSlice` (`TSFieldMapSlice`) | [`MapSlice`]                                  |
//! | `TSFieldMapEntry`                | [`FieldMapEntry`]                             |
//! | `TSLexerMode` (`TSLexMode`)      | [`LexMode`] (`reserved_word_set_id` is 0 for ABI 14) |
//! | `TSCharacterRange`, `set_contains` | [`CharacterRange`], [`set_contains`]        |
//! | `TSParseAction`, `TSParseActionEntry` | [`ParseAction`], [`ParseActionEntry`]    |
//! | `TSLexer`                        | the [`Lexer`] trait                           |
//! | `external_scanner` callbacks     | the [`ExternalScanner`] trait                 |
//! | `TSLanguage`                     | [`LanguageTables`]                            |
//! | `TSLanguageMetadata`             | [`LanguageMetadata`]                          |
//!
//! Differences from C, all deliberate:
//!
//! - Arrays are owned `Vec`s with their exact lengths, so out-of-range reads panic
//!   instead of reading other memory. `parse_actions` keeps C's layout: a header entry
//!   followed by its actions, at the same offsets the parse tables refer to.
//! - Strings are `String`s; `field_names[0]` (NULL in C) is `None`.
//! - The external scanner is a trait object made by [`ExternalScannerTables::create`]:
//!   `create` returns the scanner and `Drop` replaces C's `destroy`. `serialize` takes
//!   `&mut self` like C's `void *payload`.
//! - `lex_fn`/`keyword_lex_fn` are Rust functions over `&mut dyn Lexer`.
//! - The grammar crates decode their tables from a binary blob (see
//!   [`LanguageTables::decode`]) instead of embedding huge array literals.

use std::fmt;

/// A grammar symbol (`TSSymbol`).
pub type Symbol = u16;
/// A parse state (`TSStateId`).
pub type StateId = u16;
/// A field (`TSFieldId`).
pub type FieldId = u16;

/// `ts_builtin_sym_error`: `(TSSymbol)-1`.
pub const BUILTIN_SYM_ERROR: Symbol = Symbol::MAX;
/// `ts_builtin_sym_end`: the end-of-input token.
pub const BUILTIN_SYM_END: Symbol = 0;
/// `TREE_SITTER_SERIALIZATION_BUFFER_SIZE`: the size of the buffer external scanners
/// serialize into.
pub const SERIALIZATION_BUFFER_SIZE: usize = 1024;

/// The magic bytes that start a table blob.
pub const BLOB_MAGIC: &[u8; 8] = b"TSPORTTB";
/// The blob format version this crate decodes. The host bumps it whenever the layout
/// changes, so an old blob fails with a clear message instead of decoding garbage.
pub const BLOB_FORMAT_VERSION: u32 = 1;

/// `TSSymbolMetadata`.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct SymbolMetadata {
    pub visible: bool,
    pub named: bool,
    pub supertype: bool,
}

/// `TSMapSlice`: a run of `length` entries starting at `index` in a field or supertype
/// map.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct MapSlice {
    pub index: u16,
    pub length: u16,
}

/// `TSFieldMapEntry`.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct FieldMapEntry {
    pub field_id: FieldId,
    pub child_index: u8,
    pub inherited: bool,
}

/// `TSLexerMode` (ABI 15). ABI-14 grammars have `TSLexMode`, without
/// `reserved_word_set_id`; their modes carry 0 there, as the C runtime's
/// `ts_language_lex_mode_for_state` returns for them.
///
/// `lex_state` is `StateId::MAX` (`(TSStateId)(-1)`) for states that never lex.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct LexMode {
    pub lex_state: u16,
    pub external_lex_state: u16,
    pub reserved_word_set_id: u16,
}

/// `TSCharacterRange`: the inclusive range `start..=end` of code points.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct CharacterRange {
    pub start: i32,
    pub end: i32,
}

impl CharacterRange {
    /// A range from `start` to `end`, both inclusive.
    pub const fn new(start: i32, end: i32) -> Self {
        Self { start, end }
    }
}

/// `set_contains` from `parser.h`: whether `lookahead` falls in one of `ranges`, which
/// are sorted and disjoint. The same binary search as C, so it probes the same ranges.
/// C reads `ranges[0]` of an empty set (undefined behaviour); this returns `false`.
pub fn set_contains(ranges: &[CharacterRange], lookahead: i32) -> bool {
    if ranges.is_empty() {
        return false;
    }
    let mut index = 0usize;
    let mut size = ranges.len();
    while size > 1 {
        let half_size = size / 2;
        let mid_index = index + half_size;
        let range = &ranges[mid_index];
        if lookahead >= range.start && lookahead <= range.end {
            return true;
        } else if lookahead > range.end {
            index = mid_index;
        }
        size -= half_size;
    }
    let range = &ranges[index];
    lookahead >= range.start && lookahead <= range.end
}

/// `TSParseAction`: the C union, as an enum. The variant is C's `type`
/// (`TSParseActionTypeShift`, `...Reduce`, `...Accept`, `...Recover`).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ParseAction {
    /// `SHIFT(state)`, `SHIFT_REPEAT(state)` (`repetition`) or `SHIFT_EXTRA()`
    /// (`extra`, with `state` 0).
    Shift {
        state: StateId,
        extra: bool,
        repetition: bool,
    },
    /// `REDUCE(symbol, child_count, dynamic_precedence, production_id)`.
    Reduce {
        symbol: Symbol,
        child_count: u8,
        dynamic_precedence: i16,
        production_id: u16,
    },
    /// `ACCEPT_INPUT()`.
    Accept,
    /// `RECOVER()`.
    Recover,
}

/// `TSParseActionEntry`: either the header of an action list (`.entry`) or one of the
/// `count` actions that follow it (`.action`).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ParseActionEntry {
    /// `{.entry = {.count, .reusable}}`.
    Header { count: u8, reusable: bool },
    /// An action of the list whose header precedes it.
    Action(ParseAction),
}

impl ParseActionEntry {
    /// The action of an [`ParseActionEntry::Action`] entry. The decoder checks that the
    /// `count` entries after every header are actions, so this only panics when called
    /// on a header.
    pub fn action(&self) -> &ParseAction {
        match self {
            ParseActionEntry::Action(action) => action,
            ParseActionEntry::Header { .. } => {
                panic!("ParseActionEntry::action called on a header entry")
            }
        }
    }
}

/// `TSLanguageMetadata`: the grammar's semantic version (ABI 15 and later).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct LanguageMetadata {
    pub major_version: u8,
    pub minor_version: u8,
    pub patch_version: u8,
}

/// The Rust counterpart of `TSLexer`, the interface the lex functions and external
/// scanners use. `lexer->lookahead` is [`Lexer::lookahead`], `lexer->result_symbol`
/// is [`Lexer::result_symbol`]/[`Lexer::set_result_symbol`], and each callback is the
/// method of the same name.
pub trait Lexer {
    /// The current code point (`lexer->lookahead`): 0 at the end of input.
    fn lookahead(&self) -> i32;
    /// The symbol of the token being lexed (`lexer->result_symbol`).
    fn result_symbol(&self) -> Symbol;
    /// Sets `lexer->result_symbol`.
    fn set_result_symbol(&mut self, symbol: Symbol);
    /// `lexer->advance(lexer, skip)`: moves to the next code point; with `skip`, the
    /// current one is whitespace that does not belong to the token.
    fn advance(&mut self, skip: bool);
    /// `lexer->mark_end(lexer)`: the token ends at the current position.
    fn mark_end(&mut self);
    /// `lexer->get_column(lexer)`: the column of the current position.
    fn get_column(&mut self) -> u32;
    /// `lexer->is_at_included_range_start(lexer)`.
    fn is_at_included_range_start(&self) -> bool;
    /// `lexer->eof(lexer)`: whether the lexer is at the end of input.
    fn eof(&self) -> bool;
    /// `lexer->log(lexer, format, ...)`: debug logging; does nothing unless the lexer
    /// implements it.
    fn log(&mut self, _args: fmt::Arguments<'_>) {}
}

/// A grammar's lex function (`bool (*lex_fn)(TSLexer *, TSStateId)`): lexes one token
/// starting in `state` and returns whether it accepted one.
pub type LexFn = fn(&mut dyn Lexer, StateId) -> bool;

/// Creates a grammar's external scanner (C's `external_scanner.create`).
pub type ScannerCreateFn = fn() -> Box<dyn ExternalScanner>;

/// An external scanner: the `scan`, `serialize` and `deserialize` callbacks of a C
/// scanner, over the scanner's own state (`self`, C's `void *payload`). Dropping it
/// is `destroy`.
pub trait ExternalScanner: Send {
    /// `scan(payload, lexer, valid_symbols)`: `valid_symbols` has one flag per external
    /// token (`external_token_count` of them), indexed like the grammar's external
    /// token enum.
    fn scan(&mut self, lexer: &mut dyn Lexer, valid_symbols: &[bool]) -> bool;
    /// `serialize(payload, buffer)`: writes the scanner state into `buffer`
    /// ([`SERIALIZATION_BUFFER_SIZE`] bytes) and returns how many bytes it wrote.
    fn serialize(&mut self, buffer: &mut [u8]) -> usize;
    /// `deserialize(payload, buffer, length)`: restores the state `serialize` wrote;
    /// an empty `buffer` resets the scanner.
    fn deserialize(&mut self, buffer: &[u8]);
}

/// The `external_scanner` part of `TSLanguage`.
#[derive(Clone)]
pub struct ExternalScannerTables {
    /// `external_scanner.states`, flattened: row `i` (the valid external tokens of
    /// external lex state `i`) is `states[i * external_token_count..][..external_token_count]`.
    /// Row 0 is all `false`.
    pub states: Vec<bool>,
    /// `external_scanner.symbol_map`: the grammar symbol of each external token.
    pub symbol_map: Vec<Symbol>,
    /// Creates a scanner (C's `create`).
    pub create: ScannerCreateFn,
}

/// `TSLanguage`: every table of one grammar, with C's field names.
#[derive(Clone)]
pub struct LanguageTables {
    /// `abi_version` (`version` in ABI 14): 14 or 15.
    pub abi_version: u32,
    /// `name` (ABI 15; `None` for ABI 14).
    pub name: Option<String>,
    /// `metadata` (ABI 15; `None` for ABI 14).
    pub metadata: Option<LanguageMetadata>,
    pub symbol_count: u32,
    pub alias_count: u32,
    pub token_count: u32,
    pub external_token_count: u32,
    pub state_count: u32,
    pub large_state_count: u32,
    pub production_id_count: u32,
    pub field_count: u32,
    pub max_alias_sequence_length: u16,
    /// `parse_table`: `large_state_count * symbol_count` values, row-major
    /// (`parse_table[state * symbol_count + symbol]`).
    pub parse_table: Vec<u16>,
    /// `small_parse_table`: for each small state, a group count, then per group a value,
    /// a symbol count and that many symbols.
    pub small_parse_table: Vec<u16>,
    /// `small_parse_table_map`: the offset in `small_parse_table` of each small state
    /// (`state - large_state_count`).
    pub small_parse_table_map: Vec<u32>,
    /// `parse_actions`, at C's offsets: a terminal's value in the parse tables is the
    /// index of a [`ParseActionEntry::Header`] followed by `count` actions. See
    /// [`LanguageTables::action_list`].
    pub parse_actions: Vec<ParseActionEntry>,
    /// `symbol_names`: `symbol_count + alias_count` names.
    pub symbol_names: Vec<String>,
    /// `field_names`: `field_count + 1` names, `field_names[0]` is `None` (empty when
    /// `field_count` is 0).
    pub field_names: Vec<Option<String>>,
    /// `field_map_slices`: one per production id (empty when `field_count` is 0).
    pub field_map_slices: Vec<MapSlice>,
    pub field_map_entries: Vec<FieldMapEntry>,
    /// `symbol_metadata`: `symbol_count + alias_count` entries.
    pub symbol_metadata: Vec<SymbolMetadata>,
    /// `public_symbol_map`: `symbol_count + alias_count` entries.
    pub public_symbol_map: Vec<Symbol>,
    /// `alias_map` as in C: runs of `symbol, count, aliases...`, ended by a 0.
    pub alias_map: Vec<u16>,
    /// `alias_sequences`: `production_id_count * max_alias_sequence_length` symbols.
    pub alias_sequences: Vec<Symbol>,
    /// `lex_modes`: one per state.
    pub lex_modes: Vec<LexMode>,
    /// `lex_fn`.
    pub lex_fn: LexFn,
    /// `keyword_lex_fn` (`None` when C has NULL). The runtime calls it with state 0.
    pub keyword_lex_fn: Option<LexFn>,
    pub keyword_capture_token: Symbol,
    /// `external_scanner` (`None` when the grammar has no external tokens).
    pub external_scanner: Option<ExternalScannerTables>,
    /// `primary_state_ids`: one per state.
    pub primary_state_ids: Vec<StateId>,
    /// `reserved_words` (ABI 15): sets of `max_reserved_word_set_size` symbols each,
    /// indexed by `LexMode::reserved_word_set_id`, 0-terminated when shorter. Empty
    /// when `max_reserved_word_set_size` is 0.
    pub reserved_words: Vec<Symbol>,
    pub max_reserved_word_set_size: u16,
    /// `supertype_count` (ABI 15; 0 for ABI 14).
    pub supertype_count: u32,
    /// `supertype_symbols`: `supertype_count` symbols.
    pub supertype_symbols: Vec<Symbol>,
    /// `supertype_map_slices`: indexed by supertype symbol (one past the largest).
    pub supertype_map_slices: Vec<MapSlice>,
    pub supertype_map_entries: Vec<Symbol>,
}

impl fmt::Debug for LanguageTables {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("LanguageTables")
            .field("abi_version", &self.abi_version)
            .field("name", &self.name)
            .field("symbol_count", &self.symbol_count)
            .field("token_count", &self.token_count)
            .field("external_token_count", &self.external_token_count)
            .field("state_count", &self.state_count)
            .field("large_state_count", &self.large_state_count)
            .field("parse_actions", &self.parse_actions.len())
            .finish_non_exhaustive()
    }
}

/// Why a table blob could not be decoded.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DecodeError(pub String);

impl fmt::Display for DecodeError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::error::Error for DecodeError {}

fn fail<T>(message: impl Into<String>) -> Result<T, DecodeError> {
    Err(DecodeError(message.into()))
}

impl LanguageTables {
    /// The action list whose header is at `index` in `parse_actions` (the value the
    /// parse tables hold for a terminal): `(reusable, actions)`, where each of the
    /// `count` entries of `actions` is a [`ParseActionEntry::Action`]
    /// ([`ParseActionEntry::action`]). C reads `parse_actions[index].entry` and then
    /// `(const TSParseAction *)(entry + 1)`.
    ///
    /// Panics if `index` is not a header's index.
    pub fn action_list(&self, index: usize) -> (bool, &[ParseActionEntry]) {
        match self.parse_actions[index] {
            ParseActionEntry::Header { count, reusable } => (
                reusable,
                &self.parse_actions[index + 1..index + 1 + count as usize],
            ),
            ParseActionEntry::Action(_) => {
                panic!("parse_actions[{index}] is an action, not the header of a list")
            }
        }
    }

    /// Decodes a table blob written by the ts_port host, attaching the grammar's lex
    /// functions and external scanner.
    ///
    /// Panics with a message naming the problem when the blob is malformed, was written
    /// for another format version, or disagrees with the functions given (a keyword
    /// lex function or a scanner the tables do not expect, or a missing one).
    pub fn decode(
        blob: &[u8],
        lex_fn: LexFn,
        keyword_lex_fn: Option<LexFn>,
        scanner_create: Option<ScannerCreateFn>,
    ) -> LanguageTables {
        match Self::try_decode(blob, lex_fn, keyword_lex_fn, scanner_create) {
            Ok(tables) => tables,
            Err(error) => panic!("invalid grammar table blob: {error}"),
        }
    }

    /// [`LanguageTables::decode`], returning the problem instead of panicking.
    pub fn try_decode(
        blob: &[u8],
        lex_fn: LexFn,
        keyword_lex_fn: Option<LexFn>,
        scanner_create: Option<ScannerCreateFn>,
    ) -> Result<LanguageTables, DecodeError> {
        let mut r = Reader { data: blob, pos: 0 };
        let magic = r.take(BLOB_MAGIC.len())?;
        if magic != BLOB_MAGIC {
            return fail("not a ts_port table blob (bad magic bytes)");
        }
        let version = r.u32()?;
        if version != BLOB_FORMAT_VERSION {
            return fail(format!(
                "blob format version {version}, but this ts_port_tables decodes version \
                 {BLOB_FORMAT_VERSION}; regenerate the grammar crates with the host"
            ));
        }

        r.tag(b"HEAD")?;
        let abi_version = r.u32()?;
        let symbol_count = r.u32()?;
        let alias_count = r.u32()?;
        let token_count = r.u32()?;
        let external_token_count = r.u32()?;
        let state_count = r.u32()?;
        let large_state_count = r.u32()?;
        let production_id_count = r.u32()?;
        let field_count = r.u32()?;
        let max_alias_sequence_length = r.u16()?;
        let keyword_capture_token = r.u16()?;
        let max_reserved_word_set_size = r.u16()?;
        let supertype_count = r.u32()?;
        let has_keyword_lex_fn = r.bool()?;
        let has_external_scanner = r.bool()?;

        r.tag(b"NAME")?;
        let name = if r.bool()? { Some(r.string()?) } else { None };
        let metadata = if r.bool()? {
            Some(LanguageMetadata {
                major_version: r.u8()?,
                minor_version: r.u8()?,
                patch_version: r.u8()?,
            })
        } else {
            None
        };

        r.tag(b"PTBL")?;
        let parse_table = r.vec(Reader::u16, 2)?;
        r.tag(b"SPTB")?;
        let small_parse_table = r.vec(Reader::u16, 2)?;
        r.tag(b"SPTM")?;
        let small_parse_table_map = r.vec(Reader::u32, 4)?;
        r.tag(b"PACT")?;
        let parse_actions = r.vec(Reader::action_entry, 8)?;
        r.tag(b"SYMN")?;
        let symbol_names = r.vec(Reader::string, 4)?;
        r.tag(b"FLDN")?;
        let field_names = r.vec(
            |r| {
                if r.bool()? {
                    Ok(Some(r.string()?))
                } else {
                    Ok(None)
                }
            },
            1,
        )?;
        r.tag(b"FMSL")?;
        let field_map_slices = r.vec(Reader::map_slice, 4)?;
        r.tag(b"FMEN")?;
        let field_map_entries = r.vec(
            |r| {
                Ok(FieldMapEntry {
                    field_id: r.u16()?,
                    child_index: r.u8()?,
                    inherited: r.bool()?,
                })
            },
            4,
        )?;
        r.tag(b"SYMD")?;
        let symbol_metadata = r.vec(
            |r| {
                let bits = r.u8()?;
                if bits & !7 != 0 {
                    return fail(format!("symbol metadata byte {bits:#x} has unknown bits"));
                }
                Ok(SymbolMetadata {
                    visible: bits & 1 != 0,
                    named: bits & 2 != 0,
                    supertype: bits & 4 != 0,
                })
            },
            1,
        )?;
        r.tag(b"PSYM")?;
        let public_symbol_map = r.vec(Reader::u16, 2)?;
        r.tag(b"ALMP")?;
        let alias_map = r.vec(Reader::u16, 2)?;
        r.tag(b"ALSQ")?;
        let alias_sequences = r.vec(Reader::u16, 2)?;
        r.tag(b"LEXM")?;
        let lex_modes = r.vec(
            |r| {
                Ok(LexMode {
                    lex_state: r.u16()?,
                    external_lex_state: r.u16()?,
                    reserved_word_set_id: r.u16()?,
                })
            },
            6,
        )?;
        r.tag(b"EXTS")?;
        let external_states = r.vec(Reader::bool, 1)?;
        let external_symbol_map = r.vec(Reader::u16, 2)?;
        r.tag(b"PRIM")?;
        let primary_state_ids = r.vec(Reader::u16, 2)?;
        r.tag(b"RSVW")?;
        let reserved_words = r.vec(Reader::u16, 2)?;
        r.tag(b"SUPT")?;
        let supertype_symbols = r.vec(Reader::u16, 2)?;
        let supertype_map_slices = r.vec(Reader::map_slice, 4)?;
        let supertype_map_entries = r.vec(Reader::u16, 2)?;
        r.tag(b"END.")?;
        if r.pos != blob.len() {
            return fail(format!(
                "{} bytes left over after the end marker",
                blob.len() - r.pos
            ));
        }

        if has_keyword_lex_fn != keyword_lex_fn.is_some() {
            return fail(if has_keyword_lex_fn {
                "the tables have a keyword lex function but none was given"
            } else {
                "a keyword lex function was given but the tables have none"
            });
        }
        let external_scanner = match (has_external_scanner, scanner_create) {
            (true, Some(create)) => Some(ExternalScannerTables {
                states: external_states,
                symbol_map: external_symbol_map,
                create,
            }),
            (false, None) => {
                if !external_states.is_empty() || !external_symbol_map.is_empty() {
                    return fail("external scanner tables present without a scanner");
                }
                None
            }
            (true, None) => {
                return fail(
                    "the tables have an external scanner but no create function was given",
                );
            }
            (false, Some(_)) => {
                return fail("an external scanner was given but the tables have none");
            }
        };

        let tables = LanguageTables {
            abi_version,
            name,
            metadata,
            symbol_count,
            alias_count,
            token_count,
            external_token_count,
            state_count,
            large_state_count,
            production_id_count,
            field_count,
            max_alias_sequence_length,
            parse_table,
            small_parse_table,
            small_parse_table_map,
            parse_actions,
            symbol_names,
            field_names,
            field_map_slices,
            field_map_entries,
            symbol_metadata,
            public_symbol_map,
            alias_map,
            alias_sequences,
            lex_modes,
            lex_fn,
            keyword_lex_fn,
            keyword_capture_token,
            external_scanner,
            primary_state_ids,
            reserved_words,
            max_reserved_word_set_size,
            supertype_count,
            supertype_symbols,
            supertype_map_slices,
            supertype_map_entries,
        };
        tables.validate()?;
        Ok(tables)
    }

    /// Checks that the tables are consistent: every array has the length its counts
    /// imply, every offset and index points inside its array, and `parse_actions` is a
    /// sequence of headers each followed by its actions, with every terminal entry of
    /// the parse tables pointing at a header. [`LanguageTables::decode`] runs it, so
    /// the runtime can index the tables the way C does.
    pub fn validate(&self) -> Result<(), DecodeError> {
        let check = |ok: bool, what: String| if ok { Ok(()) } else { fail(what) };
        if !(14..=15).contains(&self.abi_version) {
            return fail(format!(
                "ABI version {} (only 14 and 15 are supported)",
                self.abi_version
            ));
        }
        let abi15 = self.abi_version >= 15;
        check(
            abi15 == self.name.is_some() && abi15 == self.metadata.is_some(),
            "name and metadata must be present exactly for ABI 15".into(),
        )?;
        let symbols = self.symbol_count as usize;
        let all_symbols = symbols + self.alias_count as usize;
        let states = self.state_count as usize;
        let large = self.large_state_count as usize;
        check(
            self.token_count <= self.symbol_count && large <= states && states <= 1 << 16,
            format!(
                "counts out of range: {} tokens, {} symbols, {large} large of {states} states",
                self.token_count, self.symbol_count
            ),
        )?;
        let len = |name: &str, actual: usize, expected: usize| {
            check(
                actual == expected,
                format!("{name} has {actual} entries, expected {expected}"),
            )
        };
        len("parse_table", self.parse_table.len(), large * symbols)?;
        len(
            "small_parse_table_map",
            self.small_parse_table_map.len(),
            states - large,
        )?;
        len("symbol_names", self.symbol_names.len(), all_symbols)?;
        len("symbol_metadata", self.symbol_metadata.len(), all_symbols)?;
        len(
            "public_symbol_map",
            self.public_symbol_map.len(),
            all_symbols,
        )?;
        len("lex_modes", self.lex_modes.len(), states)?;
        len("primary_state_ids", self.primary_state_ids.len(), states)?;
        len(
            "alias_sequences",
            self.alias_sequences.len(),
            self.production_id_count as usize * self.max_alias_sequence_length as usize,
        )?;
        check(
            self.public_symbol_map
                .iter()
                .chain(&self.alias_sequences)
                .all(|&s| (s as usize) < all_symbols),
            "public_symbol_map or alias_sequences names an unknown symbol".into(),
        )?;
        check(
            self.primary_state_ids
                .iter()
                .all(|&s| (s as usize) < states),
            "primary_state_ids names an unknown state".into(),
        )?;
        check(
            (self.keyword_capture_token as usize) < symbols,
            format!(
                "keyword_capture_token {} is not a symbol",
                self.keyword_capture_token
            ),
        )?;

        // Parse actions: headers, each followed by its actions.
        let mut is_header = vec![false; self.parse_actions.len()];
        let mut pos = 0;
        while pos < self.parse_actions.len() {
            let ParseActionEntry::Header { count, .. } = self.parse_actions[pos] else {
                return fail(format!("parse_actions[{pos}] should be a header"));
            };
            is_header[pos] = true;
            let end = pos + 1 + count as usize;
            if end > self.parse_actions.len() {
                return fail(format!("the action list at {pos} runs past the end"));
            }
            for entry in &self.parse_actions[pos + 1..end] {
                match entry {
                    ParseActionEntry::Header { .. } => {
                        return fail(format!("the action list at {pos} holds a header"));
                    }
                    ParseActionEntry::Action(ParseAction::Shift { state, .. }) => {
                        check(
                            (*state as usize) < states,
                            format!("the action list at {pos} shifts to unknown state {state}"),
                        )?;
                    }
                    ParseActionEntry::Action(ParseAction::Reduce {
                        symbol,
                        production_id,
                        ..
                    }) => {
                        check(
                            (*symbol as usize) < symbols
                                && u32::from(*production_id) < self.production_id_count.max(1),
                            format!("the action list at {pos} reduces out of range"),
                        )?;
                    }
                    ParseActionEntry::Action(_) => {}
                }
            }
            pos = end;
        }
        let check_value = |state: usize, symbol: u16, value: u16| {
            if (symbol as u32) < self.token_count {
                check(
                    is_header.get(value as usize).copied().unwrap_or(false),
                    format!(
                        "state {state}, terminal {symbol}: {value} is not an action list header"
                    ),
                )
            } else {
                check(
                    (value as usize) < states,
                    format!("state {state}, symbol {symbol}: unknown successor state {value}"),
                )
            }
        };
        for state in 0..large {
            for symbol in 0..symbols {
                let value = self.parse_table[state * symbols + symbol];
                check_value(state, symbol as u16, value)?;
            }
        }
        let table = &self.small_parse_table;
        for (i, &offset) in self.small_parse_table_map.iter().enumerate() {
            let state = large + i;
            let mut p = offset as usize;
            let mut read = || {
                let value = table.get(p).copied();
                p += 1;
                value.ok_or_else(|| {
                    DecodeError(format!("small state {state} runs past small_parse_table"))
                })
            };
            let groups = read()?;
            for _ in 0..groups {
                let value = read()?;
                let count = read()?;
                for _ in 0..count {
                    let symbol = read()?;
                    check(
                        (symbol as usize) < symbols,
                        format!("small state {state}: unknown symbol {symbol}"),
                    )?;
                    check_value(state, symbol, value)?;
                }
            }
        }

        // Fields.
        if self.field_count == 0 {
            check(
                self.field_names.len() <= 1
                    && self.field_map_slices.is_empty()
                    && self.field_map_entries.is_empty(),
                "field tables present with field_count 0".into(),
            )?;
        } else {
            len(
                "field_names",
                self.field_names.len(),
                self.field_count as usize + 1,
            )?;
            check(
                self.field_names[0].is_none() && self.field_names[1..].iter().all(Option::is_some),
                "field_names[0] must be None and the others Some".into(),
            )?;
            len(
                "field_map_slices",
                self.field_map_slices.len(),
                self.production_id_count as usize,
            )?;
        }
        check(
            self.field_map_slices
                .iter()
                .all(|s| s.index as usize + s.length as usize <= self.field_map_entries.len())
                && self
                    .field_map_entries
                    .iter()
                    .all(|e| e.field_id >= 1 && e.field_id as u32 <= self.field_count),
            "field map slices or entries out of range".into(),
        )?;

        // Aliases: runs of `symbol, count, aliases...` ended by 0.
        let mut p = 0;
        loop {
            match self.alias_map.get(p) {
                None => return fail("alias_map has no 0 terminator"),
                Some(0) => {
                    len("alias_map", self.alias_map.len(), p + 1)?;
                    break;
                }
                Some(_) => {
                    let count = *self
                        .alias_map
                        .get(p + 1)
                        .ok_or_else(|| DecodeError("alias_map ends inside a run".into()))?;
                    p += 2 + count as usize;
                }
            }
        }

        // External scanner.
        match &self.external_scanner {
            None => check(
                self.external_token_count == 0
                    && self.lex_modes.iter().all(|m| m.external_lex_state == 0),
                "external tokens or external lex states without an external scanner".into(),
            )?,
            Some(scanner) => {
                let tokens = self.external_token_count as usize;
                check(
                    tokens > 0,
                    "an external scanner with no external tokens".into(),
                )?;
                len(
                    "external_scanner.symbol_map",
                    scanner.symbol_map.len(),
                    tokens,
                )?;
                check(
                    scanner.states.len().is_multiple_of(tokens) && !scanner.states.is_empty(),
                    "external_scanner.states is not a whole number of rows".into(),
                )?;
                let rows = scanner.states.len() / tokens;
                check(
                    self.lex_modes
                        .iter()
                        .all(|m| (m.external_lex_state as usize) < rows),
                    "a lex mode names an unknown external lex state".into(),
                )?;
                check(
                    scanner.symbol_map.iter().all(|&s| (s as usize) < symbols),
                    "external_scanner.symbol_map names an unknown symbol".into(),
                )?;
            }
        }

        // Reserved words (ABI 15).
        let set_size = self.max_reserved_word_set_size as usize;
        if set_size == 0 {
            check(
                self.reserved_words.is_empty(),
                "reserved words with max_reserved_word_set_size 0".into(),
            )?;
        } else {
            check(
                abi15 && self.reserved_words.len().is_multiple_of(set_size),
                "reserved_words is not a whole number of sets".into(),
            )?;
            let sets = self.reserved_words.len() / set_size;
            check(
                self.lex_modes
                    .iter()
                    .all(|m| (m.reserved_word_set_id as usize) < sets),
                "a lex mode names an unknown reserved word set".into(),
            )?;
        }
        if !abi15 {
            check(
                self.lex_modes.iter().all(|m| m.reserved_word_set_id == 0),
                "ABI-14 lex modes with reserved word sets".into(),
            )?;
        }

        // Supertypes (ABI 15).
        len(
            "supertype_symbols",
            self.supertype_symbols.len(),
            self.supertype_count as usize,
        )?;
        let slices_needed = self
            .supertype_symbols
            .iter()
            .map(|&s| s as usize + 1)
            .max()
            .unwrap_or(0);
        len(
            "supertype_map_slices",
            self.supertype_map_slices.len(),
            slices_needed,
        )?;
        check(
            self.supertype_map_slices
                .iter()
                .all(|s| s.index as usize + s.length as usize <= self.supertype_map_entries.len())
                && self
                    .supertype_map_entries
                    .iter()
                    .all(|&s| (s as usize) < all_symbols),
            "supertype map slices or entries out of range".into(),
        )?;
        Ok(())
    }
}

/// Reads the little-endian blob format (the host's `blob.rs` writes it).
struct Reader<'a> {
    data: &'a [u8],
    pos: usize,
}

impl<'a> Reader<'a> {
    fn take(&mut self, n: usize) -> Result<&'a [u8], DecodeError> {
        match self.data.get(self.pos..self.pos + n) {
            Some(bytes) => {
                self.pos += n;
                Ok(bytes)
            }
            None => fail(format!("blob truncated at byte {}", self.pos)),
        }
    }

    fn u8(&mut self) -> Result<u8, DecodeError> {
        Ok(self.take(1)?[0])
    }

    fn bool(&mut self) -> Result<bool, DecodeError> {
        match self.u8()? {
            0 => Ok(false),
            1 => Ok(true),
            other => fail(format!("byte {other} at {} is not a bool", self.pos - 1)),
        }
    }

    fn u16(&mut self) -> Result<u16, DecodeError> {
        let bytes = self.take(2)?;
        Ok(u16::from_le_bytes([bytes[0], bytes[1]]))
    }

    fn u32(&mut self) -> Result<u32, DecodeError> {
        let bytes = self.take(4)?;
        Ok(u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]))
    }

    fn tag(&mut self, expected: &[u8; 4]) -> Result<(), DecodeError> {
        let at = self.pos;
        let found = self.take(4)?;
        if found != expected {
            return fail(format!(
                "expected section {:?} at byte {at}, found {:?}",
                String::from_utf8_lossy(expected),
                String::from_utf8_lossy(found)
            ));
        }
        Ok(())
    }

    fn string(&mut self) -> Result<String, DecodeError> {
        let len = self.u32()? as usize;
        let bytes = self.take(len)?;
        String::from_utf8(bytes.to_vec())
            .or_else(|_| fail(format!("string before byte {} is not UTF-8", self.pos)))
    }

    /// A `u32` count followed by that many items, each at least `min_size` bytes.
    fn vec<T>(
        &mut self,
        mut item: impl FnMut(&mut Self) -> Result<T, DecodeError>,
        min_size: usize,
    ) -> Result<Vec<T>, DecodeError> {
        let count = self.u32()? as usize;
        if count.saturating_mul(min_size) > self.data.len() - self.pos {
            return fail(format!(
                "array of {count} items at byte {} overruns the blob",
                self.pos
            ));
        }
        let mut items = Vec::with_capacity(count);
        for _ in 0..count {
            items.push(item(self)?);
        }
        Ok(items)
    }

    fn map_slice(&mut self) -> Result<MapSlice, DecodeError> {
        Ok(MapSlice {
            index: self.u16()?,
            length: self.u16()?,
        })
    }

    /// 8 bytes: kind, then fields by kind (see the host's `blob.rs`).
    fn action_entry(&mut self) -> Result<ParseActionEntry, DecodeError> {
        let at = self.pos;
        let kind = self.u8()?;
        let a = self.u8()?;
        let b = self.u16()?;
        let c = self.u16()?;
        let d = self.u16()?;
        let flag = |v: u16| match v {
            0 => Ok(false),
            1 => Ok(true),
            _ => fail(format!("bad flag in the parse action at byte {at}")),
        };
        Ok(match kind {
            0 => ParseActionEntry::Header {
                count: a,
                reusable: flag(b)?,
            },
            1 => ParseActionEntry::Action(ParseAction::Shift {
                state: b,
                extra: flag(c)?,
                repetition: flag(d)?,
            }),
            2 => ParseActionEntry::Action(ParseAction::Reduce {
                symbol: b,
                child_count: a,
                dynamic_precedence: c as i16,
                production_id: d,
            }),
            3 => ParseActionEntry::Action(ParseAction::Accept),
            4 => ParseActionEntry::Action(ParseAction::Recover),
            _ => return fail(format!("unknown parse action kind {kind} at byte {at}")),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ranges(pairs: &[(i32, i32)]) -> Vec<CharacterRange> {
        pairs
            .iter()
            .map(|&(a, b)| CharacterRange::new(a, b))
            .collect()
    }

    #[test]
    fn set_contains_matches_a_linear_scan() {
        let sets = [
            ranges(&[(10, 10)]),
            ranges(&[(1, 3), (5, 5)]),
            ranges(&[(36, 36), (48, 57), (65, 90), (92, 92), (95, 95), (97, 122)]),
            ranges(&[
                (0, 0),
                (2, 4),
                (7, 7),
                (9, 20),
                (30, 31),
                (40, 50),
                (60, 60),
            ]),
        ];
        for set in &sets {
            for lookahead in -2..130 {
                let linear = set
                    .iter()
                    .any(|r| r.start <= lookahead && lookahead <= r.end);
                assert_eq!(set_contains(set, lookahead), linear, "{set:?} {lookahead}");
            }
        }
        assert!(!set_contains(&[], 0));
    }

    #[test]
    fn decode_rejects_foreign_and_truncated_blobs() {
        fn lex(_: &mut dyn Lexer, _: StateId) -> bool {
            false
        }
        let error = LanguageTables::try_decode(b"nope", lex, None, None).unwrap_err();
        assert!(
            error.0.contains("truncated") || error.0.contains("magic"),
            "{error}"
        );
        let mut blob = BLOB_MAGIC.to_vec();
        blob.extend_from_slice(&99u32.to_le_bytes());
        let error = LanguageTables::try_decode(&blob, lex, None, None).unwrap_err();
        assert!(error.0.contains("format version 99"), "{error}");
    }

    #[test]
    fn action_entry_accessors() {
        let entry = ParseActionEntry::Action(ParseAction::Accept);
        assert_eq!(entry.action(), &ParseAction::Accept);
    }
}
