[package]
name = "mhr_tree_sitter_ocaml_interface"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false
description = "The OCaml (interface) grammar for mhr_tree_sitter (pure-Rust tree-sitter), from tree-sitter-ocaml 0.26.0"

[lib]
name = "tree_sitter_ocaml_interface"

[dependencies]
mhr_tree_sitter_language = { path = "../../tables" }

[dev-dependencies]
mhr_tree_sitter = { path = "../../runtime" }
